### ISSUE TITLE
Wrong file use to execute chrome driver

### ISSUE THREAD

**Issue by gmiles33** [bonigarcia/webdrivermanager#983] opened 2023-01-19 15:29 UTC
**Description of the problem**: 
When using chrome 109 there is a license file and this is getting chosen as the item to ran, and so gives an error. Looks like chromedriver added this license file in version 109.

The CacheHandler::getDriverFromCache:109 has 2 files after the filter and uses the last in the list which in my case is the license file.

**Browser and version**: Chrome 109.0.5414.74

**Operating system**: Windows 10

**WebDriverManager version**: 5.3.1

**WebDriverManager call**: WebDriverManager.chromedriver().setup();

**Error log**:  [WebDriverManager] Using chromedriver 109.0.5414.74 (resolved driver for Chrome 109)
14:49:53,872 INFO  [WebDriverManager] Exporting webdriver.chrome.driver as C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\LICENSE.chromedriver
14:50:13,965 ERROR [OsProcess] org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\LICENSE.chromedriver" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)

**Comment by bonigarcia** [comment] 2023-01-19 17:12
I am unable to reproduce this issue. Are you sure you are using WebDriverManager 5.3.1?

**Comment by jackiedaytonaAZ** [comment] 2023-02-03 21:23
We're seeing the same issue using the latest WebDriverManager version 5.3.2. It keeps trying to use the `LICENSE.chromedriver` file when using ChromeDriver v109 for Windows.

**Comment by bonigarcia** [comment] 2023-02-05 18:24
I'm still unable to reproduce this issue. In any case, I have just added an extra condition in the uncompression process to try to avoid it in the future.

**Comment by jackiedaytonaAZ** [comment] 2023-02-06 14:45
> I'm still unable to reproduce this issue. In any case, I have just added an extra condition in the uncompression process to try to avoid it in the future.

Thanks for adding that, we can do some testing once the new version is available and see how it goes.

**Comment by bonigarcia** [comment] 2023-02-06 14:59
> Maybe its the order it reads the files in.

I tried to force the reverse order, but no lock to reproduce it. In any case, maybe the latest patch fixes it.

@jackiedaytonaAZ and @gmiles33 You can try it using the snapshot version (which contains the fix).

For that, you should to bump WebDriverManager to 5.3.3-SNAPSHOT. This version (which contains the latest patch) is in the sonatype snapshots repositories. If using Maven, you also need to include the following in your pom.xml:

```
    <repositories>
        <repository>
            <id>oss.sonatype.org-snapshot</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

... or its equivalent in Gradle:

```
repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}
```

**Comment by gmiles33** [comment] 2023-02-06 15:36
Hi,

I have just tried 5.3.3-SNAPSHOT and get the same error. It works the first time only and not for the next calls.

I think the CacheHandler::getDriverFromCache:109 needs to be changed to filter out for Windows none exe files.

I have an longer trace
15:25:09,969 INFO  [Downloader] Downloading https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_win32.zip
15:25:13,940 INFO  [Downloader] Extracting driver from compressed file chromedriver_win32.zip
15:25:14,150 INFO  [WebDriverManager] Exporting webdriver.chrome.driver as C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\chromedriver.exe
15:25:14,474 ERROR [stderr] Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 38521
15:25:14,475 ERROR [stderr] Only local connections are allowed.
15:25:14,477 ERROR [stderr] Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
15:25:14,493 ERROR [stderr] ChromeDriver was started successfully.
15:25:15,393 INFO  [ProtocolHandshake] Detected dialect: W3C
15:25:33,522 INFO  [stdout] Viewable browser area in landscape mode = 1920.0 x 1080.0
15:25:41,953 INFO  [WebDriverManager] Using chromedriver 109.0.5414.74 (resolved driver for Chrome 109)
15:25:41,975 INFO  [WebDriverManager] Exporting webdriver.chrome.driver as C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\LICENSE.chromedriver
15:25:43,525 INFO  [ShrinkerThread] Exceeded maxIdleTime e30bb947-ce4a-42ca-84af-7ca4396cd48a
15:25:43,526 INFO  [ShrinkerThread] Exceeded maxIdleTime e401e54a-6173-4921-98c8-ffef58beab40
15:25:43,527 INFO  [ShrinkerThread] Exceeded maxIdleTime 40050238-1439-4a83-bc70-c66ba918ef47
15:26:01,989 ERROR [OsProcess] org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\LICENSE.chromedriver" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)
15:27:24,108 INFO  [stdout] Viewable browser area in landscape mode = 1920.0 x 1080.0
15:27:24,158 INFO  [WebDriverManager] Using chromedriver 109.0.5414.74 (resolved driver for Chrome 109)
15:27:24,180 INFO  [WebDriverManager] Exporting webdriver.chrome.driver as C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\LICENSE.chromedriver
15:27:44,201 ERROR [OsProcess] org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\username\.cache\selenium\chromedriver\win32\109.0.5414.74\LICENSE.chromedriver" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)

Image for folder where it downloads the chromedriver.

![image](https://user-images.githubusercontent.com/14803027/217014900-4f0b0b9b-9343-4e82-8333-8633f69b2528.png)

Thanks

**Comment by gmiles33** [comment] 2023-02-06 16:05
Hi,

I did delete the folder. I will have a look at putting a smaller test program together.

Thanks

**Comment by gmiles33** [comment] 2023-02-10 17:01
Hi,

I have done a small unit test, and found out the issue is only there when 'wdm.avoidTmpFolder' is true.

I have included the test I ran, the pom file is based on the pom file from main code for the webdriver.

Just run 'mvn test'

[WebDriverTest.zip](https://github.com/bonigarcia/webdrivermanager/files/10709607/WebDriverTest.zip)

Thanks

**Comment by jackiedaytonaAZ** [comment] 2023-02-17 17:22
Any updates on this?

**Comment by bonigarcia** [comment] 2023-06-12 14:49
I have just committed a patch that solves this issue. It will be available in the next version of WebDriverManager.

**Closed by bonigarcia** 2023-06-12 14:49 UTC
Labels: question
