### ISSUE TITLE
Webdriver manager is not supporting latest chrome version

### ISSUE THREAD

**Issue by ezhilarasans** [bonigarcia/webdrivermanager#1221] opened 2024-02-16 12:12 UTC
Hi Team,
I am getting error when i run my script:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 121.0.6167.184 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 

RCA: Main page it is showing the version: 114. [https://chromedriver.chromium.org/downloads]
Another page it is showing : 121 also [https://googlechromelabs.github.io/chrome-for-testing/]

<img width="1434" alt="Screenshot 2024-02-16 at 5 36 25 PM" src="https://github.com/bonigarcia/webdrivermanager/assets/51672469/6b820f73-bed3-43b6-a76e-f2295e4d4054">

**Comment by ssanagasetti** [comment] 2024-02-16 22:11
Facing the same issue, we are using web driver manager version 5.4.1 . Its downloading win32 folder in .cache/selenium and chrome driver version shows 114 instead of 121

**Comment by xinvincible21** [comment] 2024-02-17 19:16
Also seeing this issue

**Comment by DelaneyDavidSarmiento-BOL** [comment] 2024-02-18 03:42
Me too

**Comment by AnushabalanTK** [comment] 2024-02-18 07:29
Hello ,
I am observing the same issue

**Comment by gbat6086** [comment] 2024-02-19 06:40
Hello, I'm also observing this issue. Would like to see a quick response for this issue!

**Comment by netanelbendayan** [comment] 2024-02-19 07:08
same issue here
any update?

**Comment by bonigarcia** [comment] 2024-02-19 09:00
Although I am unable to reproduce this issue, it seems related to #1222. I am going to make a new release with this fix soon.

**Comment by DartBrovsky** [comment] 2024-02-19 11:09
Guys, you could try to use this guide from the official doc WebDriverManager
It helps me to solve the same issue I faced to previously.

https://bonigarcia.dev/webdrivermanager/#support-for-chromedriver-115

**Comment by diasdylan2012** [comment] 2024-02-19 12:24
> Although I am unable to reproduce this issue, it seems related to #1222. I am going to make a new release with this fix soon.

wen release?

**Comment by bbossola** [comment] 2024-02-19 14:05
Same here

**Comment by davideviviano** [comment] 2024-02-19 14:35
@bbossola hi, i have the same issue. When can i found webdrivermanager.properties ?

**Comment by colshine1** [comment] 2024-02-19 14:36
> @bbossola hi, i have the same issue. When can i found webdrivermanager.properties ?

This is the file: https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/webdrivermanager.properties#L26-L31

**Comment by davideviviano** [comment] 2024-02-19 14:38
Okei, i import the webdrivermanager with maven ,how can i solve the problem?

**Comment by bonigarcia** [comment] 2024-02-19 15:01
WebDriverManager 5.6.4 is out. This release contains the https://github.com/bonigarcia/webdrivermanager/pull/1222, which I believe should fix this issue. Maybe the cache should be cleared at least one (see [doc](https://bonigarcia.dev/webdrivermanager/#support-for-chromedriver-115)). I'm closing this issue. If the problem still happens, please open a new issue reporting all the required info in the issue template.

**Closed by bonigarcia** 2024-02-19 15:01 UTC
Labels: bug

**Comment by davideviviano** [comment] 2024-02-19 15:05
@bonigarcia Thanks

**Comment by muzammiledu** [comment] 2024-02-19 15:13
@bonigarcia, thank you for the prompt release of version 5.6.4, and @nick-etuk, your contribution to providing a fix is much appreciated. 👍

**Comment by davideviviano** [comment] 2024-02-19 15:15
> @bonigarcia, thank you for the prompt release of version 5.6.4, and @nick-etuk, your contribution to providing a fix is much appreciated. 👍

hi, did you manage the new version?

**Comment by muzammiledu** [comment] 2024-02-19 15:18
@davideviviano, Currently running the pipeline on the new version 5.6.4. Let's observe its progress to ensure a successful execution. will update how it will go.

**Comment by kdelehoidin** [comment] 2024-02-19 15:26
Unfortunately, version 5.6.4 didn't help me

**Comment by AnushabalanTK** [comment] 2024-02-19 15:36
Thank you @bonigarcia and @nick-etuk

**Comment by davideviviano** [comment] 2024-02-19 16:01
@bonigarcia it work with `WebDriverManager.chromedriver().clearDriverCache().setup()`; , thank you :-)

**Comment by muzammiledu** [comment] 2024-02-19 19:02
> > @bonigarcia, thank you for the prompt release of version 5.6.4, and @nick-etuk, your contribution to providing a fix is much appreciated. 👍
> 
> hi, did you manage the new version?

@bonigarcia @davideviviano worked for me as well.
Thanks :-)
