### ISSUE TITLE
Getting error- This version of ChromeDriver only supports Chrome version 84 for electron app automation 

### ISSUE THREAD

**Issue by vasantverma** [bonigarcia/webdrivermanager#523] opened 2020-08-07 07:00 UTC
Is it a bug or feature request - bug.
Description- I am trying to automate an electron app (in my case its postman) using selenium webdriver. I am getting the below mentioned error:
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 84
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host:  os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00BB87E3+2852835]
	Ordinal0 [0x00AA5BB1+1727409]
	Ordinal0 [0x0097E4B9+517305]
	Ordinal0 [0x00910BA0+68512]
	Ordinal0 [0x0090D3A0+54176]
	Ordinal0 [0x0092D9F7+186871]
	Ordinal0 [0x0092D7FD+186365]
	Ordinal0 [0x0092B70B+177931]
	Ordinal0 [0x00912584+75140]
	Ordinal0 [0x00913650+79440]
	Ordinal0 [0x009135E9+79337]
	Ordinal0 [0x00ABAD5C+1813852]
	GetHandleVerifier [0x00CDC616+1075574]
	GetHandleVerifier [0x00CDC367+1074887]
	GetHandleVerifier [0x00CE7497+1120247]
	GetHandleVerifier [0x00CDCC16+1077110]
	Ordinal0 [0x00AB3206+1782278]
	Ordinal0 [0x00ABC3BB+1819579]
	Ordinal0 [0x00ABC523+1819939]
	Ordinal0 [0x00AD2B45+1911621]
	BaseThreadInitThunk [0x75A76359+25]
	RtlGetAppContainerNamedObjectPath [0x77747C24+228]
	RtlGetAppContainerNamedObjectPath [0x77747BF4+180]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at BasicCommands.PostmanElectronAppTest.setup(PostmanElectronAppTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:521)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:140)
	at org.testng.TestRunner.beforeRun(TestRunner.java:645)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

Software version:
Java v1.8.0.231
Selenium- 3.141.59
WebDriverManager- 4.1.0
Chrome version- 84.0.4147.105

The selenium test file is attached to replicate the issue:

[PostmanElectronAppTest.zip](https://github.com/bonigarcia/webdrivermanager/files/5039802/PostmanElectronAppTest.zip)

**Comment by bonigarcia** [comment] 2020-08-09 14:45
The only way to trace the problem is to analyze the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level. Otherwise, it is impossible to know what is happening. I mean this kind of traces:

```
2020-07-29 23:24:52 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell.runAndWaitArray(54) -- Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', get, Version, /value]
2020-07-29 23:24:52 [main] DEBUG i.g.bonigarcia.wdm.versions.Shell.runAndWaitArray(56) -- Result: Version=84.0.4147.89
2020-07-29 23:24:52 [main] DEBUG i.g.b.wdm.versions.VersionDetector.getDriverVersionFromRepository(163) -- Latest version of chromedriver according to https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84 is 84.0.4147.30
2020-07-29 23:24:52 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.resolveDriverVersion(577) -- Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
2020-07-29 23:24:52 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(121) -- Storing resolution chrome=84 in cache (valid until 00:24:52 30/07/2020 CEST)
2020-07-29 23:24:52 [main] DEBUG i.g.b.wdm.cache.ResolutionCache.putValueInResolutionCacheIfEmpty(121) -- Storing resolution chrome84=84.0.4147.30 in cache (valid until 23:24:52 30/07/2020 CEST)
2020-07-29 23:24:52 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.logSeekRepo(879) -- Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2020-07-29 23:24:53 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.createUrlHandler(771) -- Driver to be downloaded chromedriver 84.0.4147.30
2020-07-29 23:24:53 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.downloadAndExtract(123) -- Downloading https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_win32.zip
2020-07-29 23:24:54 [main] INFO  i.g.bonigarcia.wdm.online.Downloader.extract(177) -- Extracting binary from compressed file chromedriver_win32.zip
2020-07-29 23:24:54 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(635) -- Exporting webdriver.chrome.driver as C:\Users\boni\.m2\repository\webdriver\chromedriver\win32\84.0.4147.30\chromedriver.exe
```

It seems you are not using a logger in your project (logback, log4j, etc). You can see a tutorial [here](https://www.stubbornjava.com/posts/logging-in-java-with-slf4j-and-logback) about it.

**Comment by rive91** [comment] 2020-08-11 18:34
@vasantverma I faced a similiar issue with version 3.8.0 but I resolve it by running a MVN install on my Project in Eclipse IDE, I'm not sure what was the issue but it is working now

**Comment by vasantverma-LM** [comment] 2020-08-13 04:50
@rive91 - Thanks for your reply. 
Now I am facing a different issue and I have raised an issue on selenium github page- https://github.com/SeleniumHQ/selenium/issues/8620 .

**Comment by vasantverma-LM** [comment] 2020-08-13 04:53
@bonigarcia - I got the issue working with oder version of chromedriver.exe -  ChromeDriver 2.37.544315.
Its not working with the latest chrome driver 84.0. I will raise a bug on the chromedriver community.
You can close this issue.

**Closed** 2020-08-13 11:20 UTC
Labels: question
