### ISSUE TITLE
Unzipping PhantomJs broken

### ISSUE THREAD

**Issue by Sebl29** [bonigarcia/webdrivermanager#92] opened 2016-12-12 17:21 UTC
Hi Boni,

Depending of the content of C:\Users\USER\.m2\repository\webdriver\phantomjs\windows\2.1.1\ folder, the initialization will fail.

On my maschine 
C:\Users\USER\.m2\repository\webdriver\phantomjs\windows\2.1.1\phantomjs.exe is available and it will be used successfully.
On maschines of other developers, starting their first test with PhantomJs, it will download the zip, but fail on "execution" of the zip:

org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMATION: executable: C:\Users\USER\.m2\repository\webdriver\phantomjs\windows\2.1.1\phantomjs-2.1.1-windows.zip
Dez 12, 2016 1:03:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMATION: port: 8572
Dez 12, 2016 1:03:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMATION: arguments: [--webdriver=8572, --webdriver-logfile=I:\Projects\abc\itest\phantomjsdriver.log]
Dez 12, 2016 1:03:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFORMATION: environment: {}
Dez 12, 2016 1:04:10 PM org.openqa.selenium.os.UnixProcess checkForError
SCHWERWIEGEND: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\USER\.m2\repository\webdriver\phantomjs\windows\2.1.1\phantomjs-2.1.1-windows.zip" (in directory "."): CreateProcess error=193, %1 ist keine zulässige Win32-Anwendung) 

(sorry for the german locale, taken from a chat).

**Comment by PsychoThinker** [comment] 2016-12-22 13:09
There is a problem with downloading PhantomJS from: https://npm.taobao.org/mirrors/phantomjs/ 
(at least I have this problem right now) - you may use: https://bitbucket.org/ariya/phantomjs/downloads/ instead, but I think such situations should be somehow addressed in webdrivermanager code.

**Comment by hennr** [comment] 2017-01-09 10:08
What kind of a problem, @PsychoThinker ?

Is it related to #93 ?

**Comment by PsychoThinker** [comment] 2017-01-09 10:41
@hennr Archive with PhantomJS (phantomjs-2.1.1-windows.zip) was downloaded, but not entirely (it has very small size), so it could not be unpacked.

**Comment by bonigarcia** [comment] 2017-01-10 00:08
It seems that the [taobao.org mirror for PhantomJS](https://npm.taobao.org/mirrors/phantomjs/) is not always working properly. I have changed the [default URL for PhantomJS to bitbucket.org](https://bitbucket.org/ariya/phantomjs/downloads/) in this [patch](https://github.com/bonigarcia/webdrivermanager/commit/f2646ee0ca3a1f0b7d7595c7f4819d96dc3576f8).

**Closed by bonigarcia** 2017-01-10 00:08 UTC

**Comment by patryk44** [comment] 2017-01-13 09:28
Hi Boni,

Not sure if this is the same issue but I'm getting this error which suggests that BrowserManager tries to delete directory but it is actually a file . I noticed you made a changes a few days ago to remove some bits of that code, but I don't think there is a released version that includes that changes. Could you have a look at the error below:

`Running TestSuite
09:07:57.487 Configuring TestNG with: TestNG652Configurator
09:08:00.242 2017-01-13 09:08:00 BrowserManager [INFO] Latest version of [phantomjs] is 2.5.0
09:08:00.244 2017-01-13 09:08:00 Downloader [INFO] Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz to /home/go/.m2/repository/webdriver/phantomjs/beta-linux-ubuntu-trusty-x86_64/2.5.0/phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz
09:08:04.477 2017-01-13 09:08:04 REPORTER [ERROR] Thread [1] - Error - Information: [Unhandled Exception - Class [java.lang.RuntimeException] and Message [java.lang.RuntimeException: java.lang.IllegalArgumentException: /home/go/.m2/repository/webdriver/phantomjs/beta-linux-ubuntu-trusty-x86_64/2.5.0/phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz is not a directory
09:08:04.477 	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:284)
09:08:04.477 	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:108)
09:08:04.477 	at io.github.bonigarcia.wdm.BrowserManager.setup(BrowserManager.java:87)
09:08:04.477 	at rgp.game.loader.core.factories.DriverFactory.createPhantomDriver(DriverFactory.java:42)
09:08:04.477 	at rgp.game.loader.core.factories.DriverFactory.createDriverByName(DriverFactory.java:25)
09:08:04.477 	at rgp.game.loader.core.factories.DriverFactory.create(DriverFactory.java:14)
09:08:04.477 	at rgp.game.loader.core.BaseTest.initialSetUp(BaseTest.java:22)
09:08:04.477 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:04.478 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:08:04.478 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:04.478 	at java.lang.reflect.Method.invoke(Method.java:498)
09:08:04.478 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
09:08:04.478 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
09:08:04.478 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
09:08:04.478 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
09:08:04.478 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
09:08:04.478 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
09:08:04.478 	at org.testng.TestRunner.privateRun(TestRunner.java:767)
09:08:04.478 	at org.testng.TestRunner.run(TestRunner.java:617)
09:08:04.478 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
09:08:04.478 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
09:08:04.478 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
09:08:04.479 	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
09:08:04.479 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
09:08:04.479 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
09:08:04.479 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
09:08:04.479 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
09:08:04.479 	at org.testng.TestNG.run(TestNG.java:1031)
09:08:04.479 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
09:08:04.479 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
09:08:04.479 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
09:08:04.479 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
09:08:04.479 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
09:08:04.479 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
09:08:04.479 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
09:08:04.479 Caused by: java.lang.IllegalArgumentException: /home/go/.m2/repository/webdriver/phantomjs/beta-linux-ubuntu-trusty-x86_64/2.5.0/phantomjs-2.5.0-beta-linux-ubuntu-trusty-x86_64.tar.gz is not a directory
09:08:04.480 	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1642)
09:08:04.480 	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
09:08:04.480 	at io.github.bonigarcia.wdm.Downloader.checkPhantom(Downloader.java:319)
09:08:04.480 	at io.github.bonigarcia.wdm.Downloader.extract(Downloader.java:236)
09:08:04.480 	at io.github.bonigarcia.wdm.Downloader.download(Downloader.java:131)
09:08:04.480 	at io.github.bonigarcia.wdm.BrowserManager.manage(BrowserManager.java:277)
09:08:04.480 	... 34 more
09:08:04.480 ]]`

**Comment by PsychoThinker** [comment] 2017-01-13 09:37
@patryk44 patryk44
This is related to #96

**Comment by patryk44** [comment] 2017-01-13 09:55
thanks I will try the fix by setting the driver to 2.1.1 as suggested
