### ISSUE TITLE
WebDriverManager hangs on  Ubuntu 20.04 with Chromium snap

### ISSUE THREAD

**Issue by eiswind** [bonigarcia/webdrivermanager#468] opened 2020-04-24 13:35 UTC
WebdriverManager is downloading and trying to use the downloaded version (which  does not work)

**Browser and version**:
Chromium 81 snap

**Operating system**: 
Ubuntu 20.04

**WebDriverManager version**: 
<version>3.8.1</version>

org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '***', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-26-generic', java.version: '11.0.7'
Driver info: driver.version: ChromeDriver

**Comment by eiswind** [comment] 2020-04-24 15:33
Sorry, I did oversee to use chromiumdriver instead of chromedriver.

**Comment by eiswind** [comment] 2020-04-24 15:48
when I run it with maven it downloads the driver, when It try to debug it, it detects the snap (?)
``
2020-04-24 17:45:55.464  INFO   --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Using chromedriver 81.0.4044.69 (since Chromium 81 is installed in your machine)
2020-04-24 17:45:55.497  INFO   --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2020-04-24 17:45:56.251  INFO   --- [           main] io.github.bonigarcia.wdm.Downloader      : Downloading https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
2020-04-24 17:45:56.697  INFO   --- [           main] io.github.bonigarcia.wdm.Downloader      : Extracting binary from compressed file chromedriver_linux64.zip
2020-04-24 17:45:56.782  INFO   --- [           main] i.g.bonigarcia.wdm.WebDriverManager      : Exporting webdriver.chrome.driver as /home/thomas/.m2/repository/webdriver/chromedriver/linux64/81.0.4044.69/chromedriver
```

**Comment by eiswind** [comment] 2020-04-24 16:04
OK one step forward:
``` 
WebDriverManager.chromiumdriver().clearPreferences().setup()
``` 
told me the chomium-browser command was missing,

I installed the apt package which contains the chromium-browser script in /usr/bin/chromium-browser. (Which is not there, when one install the snap only).

Now the test hangs forever  at 

```
2020-04-24 17:58:55.087 DEBUG   --- [           main] io.github.bonigarcia.wdm.Shell           : Running command on the shell: [chromium-browser, --version]
```

**Comment by eiswind** [comment] 2020-04-24 16:24
It seems to be a timing issue with the bash script. I can reproduce it in runAndWaitNoLog.
A simple fix seems to be to wait for the process before getting the output. 


``` 
@Test
    fun runAndWaitNoLogHangsForever(){
        var output = ""
        try {
            val process = ProcessBuilder("chromium-browser","--version").directory( File("."))
                    .redirectErrorStream(false).start()
            output = IOUtils.toString(process.inputStream, StandardCharsets.UTF_8)
            process.destroy()
        } catch (e: IOException) {
            e.printStackTrace()
        }
        println(output)
    }

    @Test
    fun runAndWaitNoLogWorks(){
        var output = ""
        try {
            val process = ProcessBuilder("chromium-browser","--version").directory( File("."))
                    .redirectErrorStream(false).start()
            process.waitFor()
            output = IOUtils.toString(process.inputStream, StandardCharsets.UTF_8)
            process.destroy()
        } catch (e: IOException) {
            e.printStackTrace()
        }
        println(output)
    }
```

**Comment by eiswind** [comment] 2020-04-24 16:35
I created a pull request. I think waiting for the process is smoother than killing it.

**Comment by edumco** [comment] 2020-04-25 05:39
@eiswind Is there any test that reproduce this bug or should fail on this bug?

**Comment by eiswind** [comment] 2020-04-25 06:37
@edumco I tried to set one up (you can see the code examples above), but I don't have hope because
* I guess it would hang only on 20.04
* Even the Test hangs forever, setting a timeout did't catch it

**Comment by eiswind** [comment] 2020-04-25 13:42
It looks lhe IOUtils.toString blocks at read before the process even has some output. But this is just a guess.

**Comment by bonigarcia** [comment] 2020-04-25 14:25
Thanks for contributing @eiswind. Merged.

**Closed by bonigarcia** 2020-04-25 14:25 UTC
Labels: enhancement

**Comment by bsautel** [comment] 2020-04-30 14:38
@eiswind Could you get it work with Ubuntu 20.04?

I tried using:
```java
WebDriverManager.chromiumdriver().clearPreferences().setup();
ChromeOptions options = new ChromeOptions().setHeadless(true);
WebDriver webDriver = new ChromeDriver(options);
```
But it does not work.

I get this in the logs:
> 16:28:41.567 [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 81.0.4044.69 (since Chromium 81 is installed in your machine)
16:28:41.569 [Test worker] DEBUG io.github.bonigarcia.wdm.Preferences - Storing preference chromium=81 (valid until 2020-05-01 16:28:41)
16:28:41.570 [Test worker] DEBUG io.github.bonigarcia.wdm.WebDriverManager - Found Chromium snap
16:28:41.574 [Test worker] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as **/snap/bin/chromium.chromedriver**

It successfully uses the Chromium webdriver coming from the snap package.

But after I see that:
> 1588256940096	Marionette	INFO	Stopped listening on port 45061
error : **unknown flag `port'**
2020-04-30 16:29:22.022 ERROR 253714 --- [ null to remote] org.openqa.selenium.os.OsProcess         : org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
Timed out waiting for driver server to start.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'hostname' ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-26-generic', java.version: '11.0.7'
Driver info: driver.version: ChromeDriver

It sounds like it does not work because of the unknown flag port error. Did you encounter the same issue? Does your pull request fix this issue (I can't test it since it does not seem to be released yet)?

**Comment by eiswind** [comment] 2020-04-30 14:42
This is a another known problem with selenium and snaps. Please take a look at
https://github.com/SeleniumHQ/selenium/issues/7788

You can find a quite ugly workaround there.

**Comment by bsautel** [comment] 2020-04-30 14:56
Thanks a lot @eiswind for your very quick answer. Thanks to this workaround, I can now run my tests on Ubuntu 20.04. Great!

Hope this selenium issue will be fixed soon, this workaround is not very nice...

And it sounds like I am not facing the issue you fixed thanks to your pull request, right?

**Comment by eiswind** [comment] 2020-04-30 15:28
@bsautel It seems so. I still guess that this was a timing problem on my machine. Nevertheless the fix shouldn't do any bad, at least theoretically.

**Comment by bsautel** [comment] 2020-05-01 06:50
Thanks for your explanation and your time! Don't know why I don't get the same issue as you. On my side everything is working now, even if I will be happy when the issue is fixed is Selenium and I can remove this workaround.
I did not expect this snap migration to break my webapp tests when migrating to Ubuntu 20.04... I also spent a lot of time to fix this issue. This made me discover this library which is better than the Gradle plugin I was using before, mainly because it detects the browser version and installs the corresponding driver version and also because the tests work as expected also when you don't run them via Gradle.
