### ISSUE TITLE
CONNECT refused by proxy; HTTP/1.1 407 Proxy Authentication required

### ISSUE THREAD

**Issue by shivap483** [bonigarcia/webdrivermanager#542] opened 2020-08-31 13:31 UTC
**Description of the problem**: I changed webdrivermanager version from 3.1.1 to 4.1.0/4.2.0 and it started giving proxy authentication issues. Proxy auth details are correct. It is working with webdrivermanager 3.1.1 but failing for 4.1.0 and 4.2.0

**Browser and version**: chrome version 84

**Operating system**: Windows 10 64 bit

**WebDriverManager version**: 4.1.0/4.2.0

**WebDriverManager use**: wedrivermanager.chromedriver().proxy(proxy).proxyUser(user).proxyPass(pass).browerVersion(version).setup();

**WebDriverManager traces**: 18:34:52.970 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << HTTP/1.1 407 Proxy Authentication Required
18:34:52.970 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Proxy-Authenticate: NTLM TlRMTVNTUAACAAAAHAAcADgAAAAFgomiRPSKQbJ/N20AAAAAAAAAAKYApgBUAAAACgA5OAAAAA9EAE8ATQBIAEEAUgBSAFAAUgBPAE0AQQBTAFQAAgAcAEQATwBNAEgAQQBSAFIAUABSAE8ATQBBAFMAVAABABoATgBUAFIAUgBEAEMAQgBDAEEAUAA4ADAAMAAEABAAcABuAGEAdAAuAGMAbwBtAAMALABuAHQAcgByAGQAYwBiAGMAYQBwADgAMAAwAC4AcABuAGEAdAAuAGMAbwBtAAUAEABwAG4AYQB0AC4AYwBvAG0ABwAIAEAWE1GXf9YBAAAAAA==
18:34:52.970 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Cache-Control: no-cache
18:34:52.970 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Pragma: no-cache
18:34:52.970 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Content-Type: text/html; charset=utf-8
18:34:52.971 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Proxy-Connection: Keep-Alive
18:34:52.971 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Connection: Keep-Alive
18:34:52.971 [main] DEBUG org.apache.hc.client5.http.headers - http-outgoing-3 << Content-Length: 869
18:34:52.971 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - Authentication required
18:34:52.971 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - rrdcproxy:80 requested authentication
18:34:52.971 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - Authorization challenge processed
18:34:52.972 [main] DEBUG org.apache.hc.client5.http.impl.classic.ConnectExec - Authentication failed
18:34:52.972 [main] DEBUG org.apache.hc.client5.http.impl.io.DefaultManagedHttpClientConnection - http-outgoing-3: close connection GRACEFUL
18:34:52.972 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000001: endpoint closed
18:34:52.973 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000001: endpoint closed
18:34:52.974 [main] DEBUG org.apache.hc.client5.http.impl.classic.InternalHttpClient - ep-00000001: discarding endpoint
18:34:52.974 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: releasing endpoint
18:34:52.974 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: connection is not kept alive
18:34:52.974 [main] DEBUG org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager - ep-00000001: connection released [route: {tls}->http://rrdcproxy:80->https://chromedriver.storage.googleapis.com:443][total available: 0; route allocated: 0 of 5; total allocated: 0 of 25]
18:34:52.982 [main] ERROR io.github.bonigarcia.wdm.WebDriverManager - There was an error managing chromedriver 84.0.4147.30 (org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required)
io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required
 

**Error trace**:

**Comment by bonigarcia** [comment] 2020-09-02 14:16
It seems a problem with the HTTP headers. It is missing the `Connection: keep-alive` (it was present in former versions of WebDriverManager). I have just committed a patch including that header again.

@shivap483 Could you please build WebDriverManager from the source code and check this version (`4.2.1-SNAPSHOT`) in your project?

**Comment by shivap483** [comment] 2020-09-03 08:14
Hi @bonigarcia, I have built wdm from source code and added it to my project as a Referenced Library. Still the issue exists. Attaching the traces.


[DEBUG] Removing resolution chrome=85 from cache (expired on Mon Aug 31 20:42:45 IST 2020)
[DEBUG] Running command on the shell: [wmic.exe, datafile, where, name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', get, Version, /value]
[DEBUG] Result: Version=85.0.4183.83
[DEBUG] Removing resolution chrome85=85.0.4183.38 from cache (expired on Tue Sep 01 19:42:45 IST 2020)
[WARN] Missing auth challenge
[WARN] Exception reading https://chromedriver.storage.googleapis.com/LATEST_RELEASE_85 to get latest version of chromedriver (CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required)
[DEBUG] Getting driver version for chrome85 from online versions.properties
[WARN] Missing auth challenge
[WARN] Error reading version.properties, using local instead
[INFO] Using chromedriver 85.0.4183.87 (resolved driver for Chrome 85)
[DEBUG] Storing resolution chrome=85 in cache (valid until 14:29:57 03/09/2020 IST)
[DEBUG] Storing resolution chrome85=85.0.4183.87 in cache (valid until 13:29:57 04/09/2020 IST)
[INFO] Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[WARN] Missing auth challenge
[WARN] There was an error managing chromedriver 85.0.4183.87 (org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required) ... trying again using latest driver stored in cache
[DEBUG] Resolution chrome=85 in cache (valid until 14:29:57 03/09/2020 IST)
[DEBUG] Resolution chrome85=85.0.4183.87 in cache (valid until 13:29:57 04/09/2020 IST)
[INFO] Using chromedriver 85.0.4183.87 (resolved driver for Chrome 85)
[INFO] Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[WARN] Missing auth challenge
[ERROR] There was an error managing chromedriver 85.0.4183.87 (org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required)
io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required
       at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:873)
       at io.github.bonigarcia.wdm.managers.ChromeDriverManager.getDriverUrls(ChromeDriverManager.java:101)
       at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:755)
       at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:627)
       at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:549)
       at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:746)
       at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:555)
       at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:285)
       at org.com.CommonUtils.BrowserFactories.initDriver(BrowserFactories.java:49)

**Comment by bonigarcia** [comment] 2020-09-06 19:13
I think this is a bug related to Apache HttpClient, resolved in version 5.0.1 (see for example [here](https://stackoverflow.com/questions/61039771/apache-httpclient-v5-0-doesnt-authenticate-with-ntlm-on-windows)).

WebDriverManager uses `httpclient5` version 5.0.1, in which the version should be fixed. Can you confirm you are using that version in your project?

**Comment by shivap483** [comment] 2020-09-09 04:34
Hi @bonigarcia, I'm sorry if didn't get you. How do i check what version of httpclient is used in my maven project in eclipse IDE. I have both httpclient 5.0 and 5.0.1 jar files in my .m2 repository. Also, WebDriverManager version 4.0.0 is working fine. Only  versions 4.1.0 and 4.2.0 are throwing the above mentioned issues.

**Comment by bonigarcia** [comment] 2020-09-21 14:26
In Eclipse, you can check the dependency hierarchy tab and filter by httpclient5. The version of this dependency should be 5.0.1. If you are using another version, that should be the problem.

**Comment by anilreddy** [comment] 2020-09-23 12:47
@bonigarcia I got the same issue for version 4.2.0 I have tried using `httpclient 5.0.1` and now it is working.

**Comment by shivap483** [comment] 2020-09-24 05:07
Hi @bonigarcia, Checked in my dependency hierarchy, the httpclient5 version used is 5.0.1.

**Comment by bonigarcia** [comment] 2020-09-24 09:23
@shivap483 As said by @anilreddy and explained [here](https://stackoverflow.com/questions/61039771/apache-httpclient-v5-0-doesnt-authenticate-with-ntlm-on-windows), the problem is likely to be related with the actual version used of httpclient5 in your project. It must be 5.0.1. WebDriverManager uses 5.0.1 but might be omitted in your project for a conflict with another dependency. The only idea I have for you is to force that version in your pom.xml.

**Closed by bonigarcia** 2020-09-24 09:23 UTC
Labels: question

**Comment by du-it** [comment] 2022-05-09 16:19
I still have this issue while using version 5.1.3 with Java 11 and httpclient5 5.1.3:

```
Caused by: org.apache.hc.client5.http.impl.TunnelRefusedException: CONNECT refused by proxy: HTTP/1.1 403 Forbidden
	at org.apache.hc.client5.http.impl.classic.ConnectExec.createTunnelToTarget(ConnectExec.java:259) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:145) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:175) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[httpclient5-5.1.3.jar:5.1.3]
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170) ~[httpclient5-5.1.3.jar:5.1.3]
	... 23 more
            SPOT: [14] Spot io.github.bonigarcia.wdm.config.WebDriverManagerException org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 403 Forbidden (spot with 1527 chars json)
            SPOT: [15] Spot Aborting after exception in node login.
            SPOT: [16] Spot done
            SPOT: [17] Spot summary (spot with 1987 chars json)
```

**Comment by vijay-veeranki** [comment] 2023-06-28 12:29
Hi 

We are facing the same issue, trying different versions of the webdrive

We are only seeing this issue while running it in the pipeline using headless chrome image.

Can someone suggest how we could avoid the proxy by setting no proxy?

<java.version>11</java.version>
<web-driver-manager.version>5.3.1</web-driver-manager.version>

Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 403 URLBlocked
Caused by: org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 403 URLBlocked
Caused by: org.apache.hc.client5.http.impl.TunnelRefusedException: CONNECT refused by proxy: HTTP/1.1 403 URLBlocked
