### ISSUE TITLE
geckodriver.exe is valid, but is for a machine type other than the current version - 0.32.0

### ISSUE THREAD

**Issue by DanielObretenov** [bonigarcia/webdrivermanager#925] opened 2022-10-20 10:32 UTC
**Description of the problem**: 
Selenium v.3.14

After executing WebDriverManager.firefoxdriver().setup(); with driverVersion = "" a wrong geckodriver v. 0.32.0 is downloaded - 
Driver is not started at all and when I manually try to start it from the console it gives me this message:
"geckodriver.exe is valid, but is for a machine type other than the current version"

Everything works fine with geckodriver 0.31.0. i.e driverVersion =  "0.31.0"
**Browser and version**: 
Firefox v.106
**Operating system**: 
Windows 10
**WebDriverManager version**: 
 v.4.2.2 tried with the newest but I still see the same behavior
**WebDriverManager call**: 

**WebDriverManager traces**: 

**Error log**: 
"geckodriver.exe is valid, but is for a machine type other than the current version"

**Comment by bonigarcia** [comment] 2022-11-04 09:38
I think it is related to #923. It should be fixed now.

**Closed** 2022-11-04 11:09 UTC
Labels: duplicate

**Comment by jaynlodhiya** [comment] 2022-11-08 11:08
Hello @bonigarcia I am facing this issue in the newer version 5.3.1 and in previous version also.

Currently the gecko driver downloaded from the following link:-
https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-win-aarch64.zip
Here this driver I am unable to run getting the error following:-

![Screenshot (547)](https://user-images.githubusercontent.com/41180468/200548279-94450bfa-bcaa-4f7b-89d7-31cfabd85cee.png)

But when I download manually driver from the below link and replace the driver downloaded from library:-

[geckodriver-v0.32.0-win64.zip](https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-win64.zip)
then Mozilla browser works fine.
Here need help for how to get the correct x64 driver download for  Windows 10 OS x64 system.

OS Details:-


![windows version](https://user-images.githubusercontent.com/41180468/200549099-f9b99060-0dae-4d8f-a9e1-628786b59352.PNG)

**Comment by jaynlodhiya** [comment] 2022-11-09 07:21
Hello @bonigarcia yes the issue is resolve not facing now there was problem in .m2 it was pointing to old jar library
