### ISSUE TITLE
WDM do not download latest IE driver(3.11)

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#204] opened 2018-05-02 18:52 UTC
I apologize for lots of code and text above, but I believe it's the only point to describe the issue...

I have Windows 10 x64 machine, where I'm using WDM through Selenide 4.11.2.

When I started executing test cases against IE, I've noticed that WDM creates .m2\repository\webdriver\IEDriverServer\Win32\3.10 folder instead of 3.11.

Debugging on this leads to following:
Entry point is: _.m2\repository\com\codeborne\selenide\4.11.2\selenide-4.11.2-sources.jar!\com\codeborne\selenide\webdriver\WebDriverBinaryManager.java: InternetExplorerDriverManager.getInstance().setup();_
that goes through
_protected List<URL> filterCandidateUrls(Architecture arch, String version, boolean getLatest)_
where 
candidateUrls has size of 328 (contains required 3.11 version).
In protected _List<URL> getLatest(List<URL> list, List<String> match)_ 
versionToDownload is set to 3.11 (as well as latestVersion).
_List<URL> out_
has 4 values:
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_x64_3.11.1.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_x64_3.11.0.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_Win32_3.11.1.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_Win32_3.11.0.zip

But right after calling:
_candidateUrls = urlFilter.filterByOs(candidateUrls, config().getOs());
candidateUrls = urlFilter.filterByArch(candidateUrls, arch, forcedArch);_
candidateUrls occurs to be empty...

This happens because the folder DOESN'T have the driver with _WIN64_ in it's name.

That's why then _continueSearchingVersion_ is set to true...
and at line 533 _urls = removeFromList(urls, versionToDownload);_ 
urls for 3.11 are removed... and next then _versionToDownload_ is set to null.

Then everything is repeated for version 3.10...

For 3.10:
After: 
_candidateUrls = getLatest ? getLatest(urls, getDriverName()) : getVersion(urls, getDriverName(), version);_
there two versions in the list:
https://selenium-release.storage.googleapis.com/3.10/IEDriverServer_Win32_3.10.0.zip
https://selenium-release.storage.googleapis.com/3.10/IEDriverServer_x64_3.10.0.zip
and for **some reason** after filterByOs and filterByArch it returns the only candidate:
https://selenium-release.storage.googleapis.com/3.10/IEDriverServer_Win32_3.10.0.zip
(sigh...)

1) Why driver version for 3.11 is ignored and 3.10 is downloaded?
2) Do we have a point to run filterByIgnoredVersions on empty collection?
Instead of 
if (config().getIgnoreVersions() != null) {
                candidateUrls = urlFilter.filterByIgnoredVersions(candidateUrls,
                        config().getIgnoreVersions());
            }
I'd suggest using 
if (config().getIgnoreVersions() != null **&& !candidateUrls.isEmpty()**) {
                candidateUrls = urlFilter.filterByIgnoredVersions(candidateUrls,
                        config().getIgnoreVersions());
            }

**Comment by AlexanderPoleschuk** [comment] 2018-05-04 18:00
Well, investigated it a bit deeper now and the "reason" is partlially understandable...

by the time candidateUrls = urlFilter.filterByOs(candidateUrls, config().getOs()); is called there 4 values in the list:
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_x64_3.11.1.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_x64_3.11.0.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_Win32_3.11.1.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_Win32_3.11.0.zip

After the call there only 
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_Win32_3.11.1.zip
https://selenium-release.storage.googleapis.com/3.11/IEDriverServer_Win32_3.11.0.zip
left. 
I reviewed all the releases under http://selenium-release.storage.googleapis.com/index.html page and there is no any driver that contains IEDriverServer_Win64 in its name up to the earliest available build: 2.39.
So, I in doubts it was ever working, or it was broken by a commit related to filterByOs method in WebDriverManager.java

Still don't explain why 3.10 Win32 version is downloaded then.

**Comment by bonigarcia** [comment] 2018-05-07 14:46
@AlexanderPoleschuk Thanks for reporting. Regarding your comments:

1. The problem is that IEDriverServer 3.11 is not released specifically for 64 architectures. This part of wdm has been changed recently, I remember IEDriverServer 3.11 was properly downloaded. I have committed a patch to solve it.
2. I have committed another patch improving that condition.

**Closed by bonigarcia** 2018-05-07 14:46 UTC
Labels: bug
