### ISSUE TITLE
java.lang.NumberFormatException: For input string: "public"

### ISSUE THREAD

**Issue by rychlowskipawel** [bonigarcia/webdrivermanager#1263] opened 2024-03-22 12:33 UTC
I encountered a problem with chekcing and downloading version of chromedriver.  
WebDriverManager version 5.7.0
ChromeVersion: 123.0.6312.59 

There is a problem with:
[main] (WebDriverManager.java:1219) - Using chromedriver public (resolved driver for Chrome 122)
[main] (WebDriverManager.java:1424) - There was an error managing chromedriver public (For input string: "public") ... trying again using latest driver stored in cache
[main] (WebDriverManager.java:1219) - Using chromedriver public (resolved driver for Chrome 122)
[main] (WebDriverManager.java:1413) - There was an error managing chromedriver public (For input string: "public")
java.lang.NumberFormatException: For input string: "public"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:177)
	at io.github.bonigarcia.wdm.managers.ChromeDriverManager.buildUrl(ChromeDriverManager.java:154)
	at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:1262)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1183)
	at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1430)
	at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1408)
	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:1189)
	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:426)

I checked it. Probably url has been changed on google site:
https://googlechromelabs.github.io/chrome-for-testing/#stable

In driverManager in ChromeDriverManager.class:
line 110 -> 

if (!config.isUseMirror() && !Config.isNullOrEmpty(driverVersion)) {
            String downloadUrlPattern = config.getChromeDownloadUrlPattern();
            OperatingSystem os = config.getOperatingSystem();
....
}

driverVersion parameter shouldn't be 'public'.

line 128: if (!Config.isNullOrEmpty(driverVersion) && Integer.parseInt(VersionDetector.getMajorVersion(driverVersion)) < 115) {
There is a trouble with Integer.parseInt, because in this method come string value: "public":

Dowloaded urlPatter us set as: https://storage.googleapis.com/chrome-for-testing-public/%s/%s/chromedriver-%s.zip
and it is wrong.

Please check it and prepare fix for that, thankYou

**Comment by bonigarcia** [comment] 2024-04-04 08:29
This is a duplicate of #1226. It should be fixed in the latest version of WebDriverManager. If the cache is corrupted, you should clean it -at least once- as follows:

```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

**Closed by bonigarcia** 2024-04-04 08:29 UTC
