### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 115 (Current browser version is 114.0.5735.198)

### ISSUE THREAD

**Issue by TWiStErRob** [bonigarcia/webdrivermanager#1076] opened 2023-07-19 10:03 UTC
**Description of the problem**: WDM resolves Chrome Driver 115 for Chrome 114, which is only compatible with Chrome 115, so it fails on all tests.

**Browser and version**: GitHub Actions CI, all I know is `Google Chrome 114.0.5735.198` via `google-chrome --version`

**Operating system**: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md (see also "Error log")

**WebDriverManager version**: 5.4.0 + Selenium 4.10.0

**WebDriverManager call**:
```
WebDriverManager.chromedriver()
	.avoidResolutionCache() // only added now for diagnostics, original failure was without this.
	.setup()
```

<details><summary><b>WebDriverManager traces</b>: <code>Using chromedriver 115.0.5790.98 (resolved driver for Chrome 114)</code></summary>

```
?[30m2023-07-19T09:37:47,093 TRACE [Test worker] io.github.bonigarcia.wdm.versions.VersionDetector(VersionDetector.java:356)?[m ?[1;37mReading online commands.properties to find out driver version?[m
?[36m2023-07-19T09:37:47,263 DEBUG [Test worker] jdk.event.security(LoggingProviderImpl.java:274)?[m ?[1;37m TLSHandshake: raw.githubusercontent.com:443, TLSv1.3, TLS_AES_256_GCM_SHA384, -1906729876?[m
?[36m2023-07-19T09:37:47,295 DEBUG [Test worker] io.github.bonigarcia.wdm.versions.VersionDetector(VersionDetector.java:245)?[m ?[1;37mDetecting chrome version using online commands.properties?[m
?[36m2023-07-19T09:37:47,297 DEBUG [Test worker] io.github.bonigarcia.wdm.versions.Shell(Shell.java:65)?[m ?[1;37mRunning command on the shell: [google-chrome, --version]?[m
?[36m2023-07-19T09:37:47,336 DEBUG [Test worker] io.github.bonigarcia.wdm.versions.Shell(Shell.java:69)?[m ?[1;37mResult: Google Chrome 114.0.5735.198?[m
?[30m2023-07-19T09:37:47,337 TRACE [Test worker] io.github.bonigarcia.wdm.versions.VersionDetector(VersionDetector.java:324)?[m ?[1;37mDetected browser version is 114.0.5735.198?[m
?[36m2023-07-19T09:37:47,406 DEBUG [Test worker] jdk.event.security(LoggingProviderImpl.java:274)?[m ?[1;37m TLSHandshake: googlechromelabs.github.io:443, TLSv1.3, TLS_AES_256_GCM_SHA384, -1906729876?[m
?[32m2023-07-19T09:37:47,544 INFO  [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1212)?[m ?[1;37mUsing chromedriver 115.0.5790.98 (resolved driver for Chrome 114)?[m
?[30m2023-07-19T09:37:47,546 TRACE [Test worker] io.github.bonigarcia.wdm.cache.CacheHandler(CacheHandler.java:83)?[m ?[1;37mChecking if chromedriver exists in cache?[m
?[30m2023-07-19T09:37:47,555 TRACE [Test worker] io.github.bonigarcia.wdm.cache.CacheHandler(CacheHandler.java:119)?[m ?[1;37mchromedriver not found in cache?[m
?[32m2023-07-19T09:37:47,558 INFO  [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1564)?[m ?[1;37mReading https://chromedriver.storage.googleapis.com/ to seek chromedriver?[m
?[36m2023-07-19T09:37:47,664 DEBUG [Test worker] jdk.event.security(LoggingProviderImpl.java:274)?[m ?[1;37m TLSHandshake: chromedriver.storage.googleapis.com:443, TLSv1.3, TLS_AES_256_GCM_SHA384, 975562421?[m
?[30m2023-07-19T09:37:48,175 TRACE [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1429)?[m ?[1;37mAll driver URLs: [MOVED TO ATTACHMENT, BECAUSE GITHUB COMMENTS CANNOT HANDLE 65k+ comments]?[m
?[36m2023-07-19T09:37:48,195 DEBUG [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1449)?[m ?[1;37mDriver to be downloaded chromedriver 115.0.5790.98?[m
?[30m2023-07-19T09:37:48,197 TRACE [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1458)?[m ?[1;37mDriver URLs after filtering for version: []?[m
?[30m2023-07-19T09:37:48,197 TRACE [Test worker] io.github.bonigarcia.wdm.online.UrlHandler(UrlHandler.java:141)?[m ?[1;37mURLs before filtering by OS (LINUX): []?[m
?[30m2023-07-19T09:37:48,199 TRACE [Test worker] io.github.bonigarcia.wdm.online.UrlHandler(UrlHandler.java:145)?[m ?[1;37mURLs after filtering by OS (LINUX): []?[m
?[30m2023-07-19T09:37:48,200 TRACE [Test worker] io.github.bonigarcia.wdm.online.UrlHandler(UrlHandler.java:151)?[m ?[1;37mURLs before filtering by architecture (64): []?[m
?[30m2023-07-19T09:37:48,200 TRACE [Test worker] io.github.bonigarcia.wdm.online.UrlHandler(UrlHandler.java:160)?[m ?[1;37mURLs after filtering by architecture (64): []?[m
?[30m2023-07-19T09:37:48,201 TRACE [Test worker] io.github.bonigarcia.wdm.online.UrlHandler(UrlHandler.java:127)?[m ?[1;37mURLs before filtering by beta versions: []?[m
?[30m2023-07-19T09:37:48,202 TRACE [Test worker] io.github.bonigarcia.wdm.online.UrlHandler(UrlHandler.java:134)?[m ?[1;37mURLs after filtering by beta versions: []?[m
?[36m2023-07-19T09:37:48,207 DEBUG [Test worker] io.github.bonigarcia.wdm.WebDriverManager(ChromeDriverManager.java:156)?[m ?[1;37mUsing URL built from repository pattern: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.98/linux64/chromedriver-linux64.zip?[m
?[30m2023-07-19T09:37:48,223 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:123)?[m ?[1;37mTarget file for URL https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.98/linux64/chromedriver-linux64.zip driver version 115.0.5790.98 = /home/runner/.cache/selenium/chromedriver/linux64/115.0.5790.98/chromedriver-linux64.zip?[m
?[32m2023-07-19T09:37:48,223 INFO  [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:131)?[m ?[1;37mDownloading https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.98/linux64/chromedriver-linux64.zip?[m
?[30m2023-07-19T09:37:48,225 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:137)?[m ?[1;37mTarget folder /home/runner/.cache/selenium/chromedriver/linux64/115.0.5790.98 ... using temporal file /tmp/17348195422978868437/chromedriver-linux64.zip?[m
?[36m2023-07-19T09:37:48,274 DEBUG [Test worker] jdk.event.security(LoggingProviderImpl.java:274)?[m ?[1;37m TLSHandshake: edgedl.me.gvt1.com:443, TLSv1.3, TLS_AES_256_GCM_SHA384, 90290686?[m
?[32m2023-07-19T09:37:48,541 INFO  [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:192)?[m ?[1;37mExtracting driver from compressed file chromedriver-linux64.zip?[m
?[30m2023-07-19T09:37:48,542 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:220)?[m ?[1;37mUnzipping chromedriver-linux64/LICENSE.chromedriver (size: 280041 KB, compressed size: 68890 KB)?[m
?[30m2023-07-19T09:37:48,544 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:220)?[m ?[1;37mUnzipping chromedriver-linux64/chromedriver (size: 13547232 KB, compressed size: 7161250 KB)?[m
?[30m2023-07-19T09:37:48,664 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:330)?[m ?[1;37mDeleting file /tmp/17348195422978868437/chromedriver-linux64.zip?[m
?[30m2023-07-19T09:37:48,665 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:330)?[m ?[1;37mDeleting file /tmp/17348195422978868437/chromedriver-linux64/LICENSE.chromedriver?[m
?[30m2023-07-19T09:37:48,666 TRACE [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1303)?[m ?[1;37mFound driver in post-download: /tmp/17348195422978868437/chromedriver-linux64/chromedriver?[m
?[30m2023-07-19T09:37:48,667 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:340)?[m ?[1;37mDeleting folder /tmp/17348195422978868437?[m
?[30m2023-07-19T09:37:48,667 TRACE [Test worker] io.github.bonigarcia.wdm.online.Downloader(Downloader.java:163)?[m ?[1;37mDriver after extraction /home/runner/.cache/selenium/chromedriver/linux64/115.0.5790.98/chromedriver?[m
?[32m2023-07-19T09:37:48,668 INFO  [Test worker] io.github.bonigarcia.wdm.WebDriverManager(WebDriverManager.java:1265)?[m ?[1;37mExporting webdriver.chrome.driver as /home/runner/.cache/selenium/chromedriver/linux64/115.0.5790.98/chromedriver?[m
?[32m2023-07-19T09:37:48,692 INFO  [Test worker] org.openqa.selenium.remote.service.DriverService(DriverService.java:468)?[m ?[1;37mDriver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output?[m
?[36m2023-07-19T09:37:48,825 DEBUG [Test worker] jdk.internal.httpclient.debug(LoggingProviderImpl.java:286)?[m ?[1;37m[Test worker] [33ms] HttpClientImpl(1) proxySelector is sun.net.spi.DefaultProxySelector@4f8d86e4 (user-supplied=false)?[m
?[36m2023-07-19T09:37:48,863 DEBUG [Forwarding newSession on session null to remote] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java:657)?[m ?[1;37mExecuting: newSession [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless, --window-size=1920,1080], extensions: []}}]}]?[m
?[36m2023-07-19T09:37:48,865 DEBUG [Forwarding newSession on session null to remote] org.openqa.selenium.remote.service.DriverService(DriverService.java:209)?[m ?[1;37mStarting driver at /home/runner/.cache/selenium/chromedriver/linux64/115.0.5790.98/chromedriver with [--port=17043, --log-level=WARNING]?[m
?[36m2023-07-19T09:37:48,930 DEBUG [Driver Service Executor] org.openqa.selenium.net.UrlChecker(UrlChecker.java:59)?[m ?[1;37mWaiting for [http://localhost:17043/status]?[m
?[36m2023-07-19T09:37:48,934 DEBUG [UrlChecker-2] org.openqa.selenium.net.UrlChecker(UrlChecker.java:73)?[m ?[1;37mPolling http://localhost:17043/status?[m
?[36m2023-07-19T09:37:49,018 DEBUG [Forwarding newSession on session null to remote] org.openqa.selenium.remote.http.jdk.JdkHttpClient(JdkHttpClient.java:356)?[m ?[1;37mExecuting request: (POST) /session?[m
?[36m2023-07-19T09:37:49,058 DEBUG [Forwarding newSession on session null to remote] jdk.internal.httpclient.debug(LoggingProviderImpl.java:286)?[m ?[1;37m[Forwarding newSession on session null to remote] [267ms] HttpClientImpl(1) ClientImpl (async) send http://localhost:17043/session POST?[m
	 proxy=null?[m
?[36m2023-07-19T09:37:53,609 DEBUG [Forwarding newSession on session null to remote] org.openqa.selenium.remote.http.jdk.JdkHttpClient(JdkHttpClient.java:439)?[m ?[1;37mEnding request (POST) /session in 4591ms?[m
?[36m2023-07-19T09:37:53,642 DEBUG [Forwarding newSession on session null to remote] org.openqa.selenium.net.UrlChecker(UrlChecker.java:109)?[m ?[1;37mWaiting for http://localhost:17043/shutdown?[m
?[36m2023-07-19T09:37:53,643 DEBUG [UrlChecker-2] org.openqa.selenium.net.UrlChecker(UrlChecker.java:119)?[m ?[1;37mPolling http://localhost:17043/shutdown?[m
?[36m2023-07-19T09:37:53,660 DEBUG [UrlChecker-2] org.openqa.selenium.net.UrlChecker(UrlChecker.java:119)?[m ?[1;37mPolling http://localhost:17043/shutdown?[m
?[36m2023-07-19T09:37:53,694 DEBUG [Forwarding newSession on session null to remote] org.openqa.selenium.remote.RemoteWebDriver(RemoteWebDriver.java:663)?[m ?[1;37mException: newSession Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 115
Current browser version is 114.0.5735.198 with binary path /usr/bin/google-chrome 
Host info: host: 'fv-az341-70', ip: '10.1.1.24'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1041-azure', java.version: '11.0.19'
Driver info: driver.version: ChromeDriver?[m
```
[driver_urls.txt](https://github.com/bonigarcia/webdrivermanager/files/12093696/driver_urls.txt)

</details>

<details><summary><b>Error log</b>: <code>Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 115</code></summary>

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 115
Current browser version is 114.0.5735.198 with binary path /usr/bin/google-chrome 
Host info: host: 'fv-az341-70', ip: '10.1.1.24'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1041-azure', java.version: '11.0.19'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --headless, --window-size=1920,1080], extensions: []}}]}]
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
	at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
	at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at app//org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at app//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
	at app//org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227)
	at app//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154)
	at app//org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:107)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:87)
	at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
	at app//net.twisterrob.web.test.Browser.createDriver(Browser.kt:40)
	at app//net.twisterrob.web.test.WebDriverExtension.beforeEach(WebDriverExtension.kt:13)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:166)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:202)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:202)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:165)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:132)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.19/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base@11.0.19/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at app//org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.19/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.19/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.19/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
	Suppressed: java.lang.NullPointerException
		at net.twisterrob.web.test.WebDriverExtension.afterEach(WebDriverExtension.kt:17)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$12(TestMethodTestDescriptor.java:260)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:276)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:276)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:275)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:259)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:144)
		... 63 more
```

</details>

**Comment by fborgespmd** [comment] 2023-07-19 10:45
Hi @TWiStErRob are you going to deploy a new patch to fix this issue?
Do we have a way to go around it in the meantime?

**Comment by TWiStErRob** [comment] 2023-07-19 10:52
@fborgespmd I'm a Contributor only (that means I have some PRs merged to a repo, and in my case it was [this huge change 😅](https://github.com/bonigarcia/webdrivermanager/pull/736/files)). Only Collaborators/Members can decide/release.

**Comment by fborgespmd** [comment] 2023-07-19 10:58
> 

Thank @TWiStErRob , sorry for the confusion. 

We tried to updated wdm.chromeDriverVersion to be 114, but I guess it's being ignored. Do you by any chance know why is that happening?

**Comment by TWiStErRob** [comment] 2023-07-19 10:59
No clue yet, I'm looking at that workaround too now. Check the WDM logs maybe they reveal something.

**Comment by TWiStErRob** [comment] 2023-07-19 11:02
Ah, actually I have an idea: try without cache, see `WebDriverManager call` in OP above.

**Comment by TWiStErRob** [comment] 2023-07-19 11:05
It also depends on the version you're using, I tried the one that was successful yesterday, but got:
```
io.github.bonigarcia.wdm.online.HttpClient(HttpClient.java:176)
Error HTTP 404 executing https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.133/win64/chromedriver-win64.zip
```
I have a feeling they might have different versions for different OSs. My CI is linux (that's where I got the number), but I'm trying on Windows 10 x64.

**Comment by TWiStErRob** [comment] 2023-07-19 11:15
I managed to make it work on Windows 10 with `wdm.chromeDriverVersion=114.0.5735.90` and on GitHub Actions `ubuntu-latest` with `wdm.chromeDriverVersion=114.0.5735.133`.

**Comment by bonigarcia** [comment] 2023-07-19 11:25
I confirmed this issue. The problem is that, as of version 5.4.0, WebDriverManager relies on the [Chrome for Testing](https://googlechromelabs.github.io/chrome-for-testing/) (CfT) endpoints to discover the proper versions of chromedriver. Today, for the first time, the latest stable version is Chrome 115, and therefore, chromedriver 115. The problem happens when the browser is still Chrome 114, which, unfortunately, is not compatible with chromedriver 115.

The quick solution to this problem is to **update to Chrome 115**. And, just in case, also the driver cache needs to be cleaned (at least the first time):

```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

**Comment by TWiStErRob** [comment] 2023-07-19 11:28
@bonigarcia thanks for the explanation!

> The quick solution to this problem is to update to Chrome 115.

Yeah, tell that to GitHub Actions runner maintainers :) I guess https://github.com/browser-actions/setup-chrome would be an option, but I'm ok downgrading the driver instead.

> The problem happens when the browser is still Chrome 114, which, unfortunately, is not compatible with chromedriver 115.

Does this happen every major Chrome bump, or just some?

**Comment by bonigarcia** [comment] 2023-07-19 11:31
> Does this happen every major Chrome bump, or just some?

This specific problem should only happen now (the transition to CfT endpoints, i.e. Chrome 114 to 115).

**Comment by bonigarcia** [comment] 2023-07-19 11:38
Another solution to this problem is to use [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) directly. Selenium Manager is the official "manager" for Selenium. It has been released as of Selenium 4.6.0, and as of Selenium 4.10.0, it also uses the CfT endpoints. I implemented the Rust logic of Selenium Manager, and I believe this problem should not happen with it.

Using Selenium Manager is straightforward. Simply remove the WebDriverManager call from your test, and Selenium Manager will make the automated driver management magic for you (in the same way that WebDriverManager).

**Comment by tbrandirali** [comment] 2023-07-19 12:15
@bonigarcia updating chrome and clearing the driver cache with the above method did not work for us. What did the trick was fixing the driver version like so:
```java
WebDriverManager.chromedriver().driverVersion("114.0.5735.90").setup();
```
We're using Selenide though...

**Comment by wildpioneer** [comment] 2023-07-19 12:38
Starting with M115 the latest Chrome + ChromeDriver releases per release channel (Stable, Beta, Dev, Canary) are available at[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). For automated version downloading one can use the convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json).

**Comment by TWiStErRob** [comment] 2023-07-19 12:53
@wildpioneer yes, that's the problem here, we're still on Chrome 114, and the "last-known-good" driver is not compatible with that.

**Closed** 2023-07-19 13:39 UTC
Labels: bug

**Comment by bonigarcia** [comment] 2023-07-19 14:21
WebDriverManager still have features not implemented in Selenium Manager (e.g., browsers in Docker or monitoring). But it you use only WebDriverManager for driver management, you can migrate to Selenium Manager (it is still on beta, but it's working nicely).

**Comment by lcaravsseg** [comment] 2024-02-20 13:18
Buenos días!
Después de intentar varias de las soluciones propuestas y no obtener resultados positivos borramos completamente la capeta "selenium" ubicada en C:\WINDOWS\system32\config\systemprofile\.cache y resolvimos el problema.

El archivo resolution.properties mostraba conflictos entre versiones del chrome y chromedriver.

Saludos!
