### ISSUE TITLE
Webdriver run from a service cannot run program wmic for retrieving chrome version.

### ISSUE THREAD

**Issue by nzall** [bonigarcia/webdrivermanager#281] opened 2018-12-04 10:18 UTC
I have configured my webdriver code as follows:

```
WebDriverManager.chromedriver().setup();
        	// webDriver = new ChromeDriver();
            ChromeOptions options = new ChromeOptions();
            
            // ChromeDriver is just AWFUL because every version or two it breaks unless you pass cryptic arguments
            //AGRESSIVE: options.setPageLoadStrategy(PageLoadStrategy.NONE); // https://www.skptricks.com/2018/08/timed-out-receiving-message-from-renderer-selenium.html
            options.addArguments("--enable-automation"); // https://stackoverflow.com/a/43840128/1689770
            options.addArguments("--headless"); // only if you are ACTUALLY running headless
            options.addArguments("--no-sandbox"); //https://stackoverflow.com/a/50725918/1689770
            options.addArguments("--disable-infobars"); //https://stackoverflow.com/a/43840128/1689770
            options.addArguments("--disable-dev-shm-usage"); //https://stackoverflow.com/a/50725918/1689770
            options.addArguments("--disable-gpu"); //https://stackoverflow.com/questions/51959986/how-to-solve-selenium-chromedriver-timed-out-receiving-message-from-renderer-exc
            options.addArguments("--window-size=1920,1080");
            options.addArguments("--start-maximized");
            options.addArguments("--disable-extensions");
            options.addArguments("--bwsi");
            options.addArguments("--user-data-dir="+ System.getProperty("test.web.chrome.data.dir") +"/user-data-dir");
            try {
    			File logFile = new File(System.getProperty("test.web.chrome.data.dir").replace("/", "\\") + "\\logs\\chromedriver.log");
    			logFile.getParentFile().mkdirs();
    			logFile.createNewFile();
            	ChromeDriverService driverService = new Builder().withVerbose(true).withLogFile(logFile).build();
         
				
				webDriver = new ChromeDriver(driverService, options);
			} catch (IOException e) {
				LOGGER.error(e);
				webDriver = new ChromeDriver(options);
			}
```

I get the below warning when running the above code:

 ```
[testng] 2018-11-15 12:22:00,657 [main] WARN  Shell - There was an error executin commannd [wmic, datafile, where, name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', get, Version, /value] on the shell
   [testng] java.io.IOException: Cannot run program "wmic": CreateProcess error=2, The system cannot find the file specified
   [testng] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
   [testng] 	at io.github.bonigarcia.wdm.Shell.runAndWaitNoLog(Shell.java:59)
   [testng] 	at io.github.bonigarcia.wdm.Shell.runAndWaitArray(Shell.java:50)
   [testng] 	at io.github.bonigarcia.wdm.Shell.runAndWait(Shell.java:44)
   [testng] 	at io.github.bonigarcia.wdm.WebDriverManager.getDefaultBrowserVersion(WebDriverManager.java:959)
   [testng] 	at io.github.bonigarcia.wdm.ChromeDriverManager.getBrowserVersion(ChromeDriverManager.java:68)
   [testng] 	at io.github.bonigarcia.wdm.WebDriverManager.getVersionForInstalledBrowser(WebDriverManager.java:477)
   [testng] 	at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:430)
   [testng] 	at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:229)
   [testng] 	at mynamespace.test.web.webdriver.WebDriverConfiguration.createWebDriver(WebDriverConfiguration.java:113)
   [testng] 	at mynamespace.test.web.webdriver.webpad.WebpadSetupTest.setup(WebpadSetupTest.java:48)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   [testng] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   [testng] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   [testng] 	at java.lang.reflect.Method.invoke(Method.java:498)
   [testng] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
   [testng] 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
   [testng] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
   [testng] 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
   [testng] 	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
   [testng] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
   [testng] 	at org.testng.TestRunner.privateRun(TestRunner.java:774)
   [testng] 	at org.testng.TestRunner.run(TestRunner.java:624)
   [testng] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
   [testng] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
   [testng] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
   [testng] 	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
   [testng] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
   [testng] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
   [testng] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
   [testng] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
   [testng] 	at org.testng.TestNG.run(TestNG.java:1048)
   [testng] 	at org.testng.TestNG.privateMain(TestNG.java:1355)
   [testng] 	at org.testng.TestNG.main(TestNG.java:1324)
   [testng] Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
   [testng] 	at java.lang.ProcessImpl.create(Native Method)
   [testng] 	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
   [testng] 	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
   [testng] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
   [testng] 	... 33 more

```
When I execute the command from the command line, it works:

C:\Users\nak>wmic datafile where name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe' get Version /value

Version=70.0.3538.110

Maybe something that complicates the situation is that I'm running my Selenium tests using an Ant script started by a service which runs as .\Administrator.

**Comment by bonigarcia** [comment] 2018-12-04 21:35
Maybe this is caused by a path issue. I've just committed a patch to try to avoid in by running wmic on system32 folder in Windows machines. It will be available on next version of WebDriverManager.

**Closed by bonigarcia** 2018-12-04 21:35 UTC
Labels: enhancement
