### ISSUE TITLE
Chrome driver 114 is being downloaded when 121 is expected

### ISSUE THREAD

**Issue by adityai** [bonigarcia/webdrivermanager#1231] opened 2024-02-20 21:55 UTC
Using the latest 5.6.4 version of the driver.

The web driver manager is consistently downloading chrome driver version 114 when version 121 is expected. 

This started happening with version 5.4.1 that I was using earlier today. Even with 5.6.4 we I am seeing the same issue.

**Comment by adityai** [comment] 2024-02-20 23:36
The content of selenium resolution.properties file (.cache\selenium\resolution.properties):

#WebDriverManager Resolution Cache
#Tue Feb 20 15:34:12 PST 2024
chrome=121
chrome121=114.0.5735.90
chrome121-ttl=15\:34\:12 21/02/2024 PST
chrome-ttl=16\:34\:12 20/02/2024 PST

**Comment by adityai** [comment] 2024-02-21 00:07
I deleted the resolution.properties file from cache and re-ran the test. The chrome121=114.0.5735.90 property is in the new file as well.

**Comment by Ramji19** [comment] 2024-02-21 09:03
Facing the same issue as reported above

**Comment by bonigarcia** [comment] 2024-02-21 10:46
Not sure, but I believe it is a duplicate of #1226.

**Closed by bonigarcia** 2024-02-21 10:46 UTC
