### ISSUE TITLE
It does not work with Gitlab pipeline

### ISSUE THREAD

**Issue by QA-Rahul** [bonigarcia/webdrivermanager#491] opened 2020-05-30 15:22 UTC
I am using the latest version of it but still, it's not working on GitLab pipeline

![image](https://user-images.githubusercontent.com/18675695/83332140-2283cf80-a2b7-11ea-833e-89896c524f7f.png)

**Description of the problem**: 

**Browser and version**: 

**Operating system**: System info: host: 'runner-ed2dce3a-project-16458807-concurrent-0', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.78-coreos', java.version: '1.8.0_252'

**WebDriverManager version**: `4.0.0`

**WebDriverManager use**:  
`
ChromeOptions options = new ChromeOptions();
                        options.addArguments("--start-maximized");
                        options.addArguments("--headless");
                        options.addArguments("--window-size=1366,768");
                        options.addArguments("--no-sandbox");
                        options.addArguments("--disable-popup-blocking");
                        options.addArguments("--disable-dev-shm-usage");
                        options.addArguments("--disable-gpu");
                        options.addArguments("--dns-prefetch-disable");
                        options.addArguments("--always-authorize-plugins");
                        options.addArguments("enable-automation");
                        options.addArguments("--disable-browser-side-navigation");
                        options.addArguments("--ignore-certificate-errors");
                        options.addArguments("--disable-extensions");
                        WebDriverManager.chromedriver().setup();
                        driver = new ChromeDriver(options);
                        driver.manage().window().maximize();
`

**WebDriverManager traces**: 
```
Running TestSuite
 @browser
 Feature: Login section
 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
 SLF4J: Defaulting to no-operation (NOP) logger implementation
 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
 /root/.m2/repository/webdriver/chromedriver/linux64/83.0.4103.39/chromedriver: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
 May 30, 2020 3:16:17 PM org.openqa.selenium.os.OsProcess checkForError
 SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)
 Unable to load browser: Timed out waiting for driver server to start.
 Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'
 System info: host: 'runner-ed2dce3a-project-16458807-concurrent-0', ip: '172.17.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.78-coreos', java.version: '1.8.0_252'
 Driver info: driver.version: ChromeDriver
```

**Comment by bonigarcia** [comment] 2020-05-31 17:24
The only way to trace the problem is to analyse the WebDriverManager traces (`io.github.bonigarcia.wdm.*`) at `DEBUG` level. Otherwise, it is impossible to know what is happening. I mean this kind of traces:

```
2020-03-10 17:00:38 [main] DEBUG io.github.bonigarcia.wdm.Shell.runAndWaitArray(55) -- Running command on the shell: [wmic, datafile, where, name='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', get, Version, /value]
2020-03-10 17:00:38 [main] DEBUG io.github.bonigarcia.wdm.Shell.runAndWaitArray(57) -- Result: Version=80.0.3987.132
2020-03-10 17:00:38 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.getDriverVersionForBrowserFromProperties(687) -- Getting driver version for chrome80 from online versions.properties
2020-03-10 17:00:39 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.detectDriverVersionFromBrowser(617) -- Using chromedriver 80.0.3987.106 (since Google Chrome 80 is installed in your machine)
2020-03-10 17:00:39 [main] DEBUG io.github.bonigarcia.wdm.Preferences.putValueInPreferencesIfEmpty(66) -- Storing preference chrome=80 (valid until 2020-03-11 17:00:39)
2020-03-10 17:00:39 [main] DEBUG io.github.bonigarcia.wdm.Preferences.putValueInPreferencesIfEmpty(66) -- Storing preference chrome80=80.0.3987.106 (valid until 2020-03-11 17:00:39)
2020-03-10 17:00:39 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.downloadAndExport(566) -- Driver chromedriver 80.0.3987.106 found in cache
2020-03-10 17:00:39 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1115) -- Exporting webdriver.chrome.driver as C:\Users\boni\.m2\repository\webdriver\chromedriver\win32\80.0.3987.106\chromedriver.exe
```

It seems you are not using a logger in your project (logback, log4j, etc). You can see a tutorial [here](https://www.stubbornjava.com/posts/logging-in-java-with-slf4j-and-logback) about it.

**Comment by QA-Rahul** [comment] 2020-06-01 17:56
Sure. I will implement log and post here.

**Comment by eliasnogueira** [comment] 2020-06-05 07:10
@QA-Rahul this error is not related to the webdrivermanager.

**Basic explanation**
When you run a browser test on a pipeline the executor (most of the time a docker image) does not have the graphical user interface. Because of that, you have that error.
You can see the same error on the link below, where I'm trying to run a test with a docker image without chrome and without set the Chrome option as headless.
https://gitlab.com/elias.nogueira/webdrivermanager-pipeline-test/-/jobs/581828359

If you want to run your tests with webdrivermanager in a pipeline you must:
1. provide an image that contains java + (maven or grade) + chrome
2. set an option to chrome use the headless mode

For item 1, you can try to find a public docker image on the docker hub. You can also use the same image I'm using: https://gitlab.com/elias.nogueira/webdrivermanager-pipeline-test/-/blob/master/.gitlab-ci.yml#L1

For item 2, you can see an example here: https://gitlab.com/elias.nogueira/webdrivermanager-pipeline-test/-/blob/master/src/test/java/com/eliasnogueira/wdm/GithubWDMPageTest.java#L22-25

@bonigarcia what do you think about a short explanation on the readme file telling the problems or requirements to remember when you use it in a pipeline?
It's actually not related to WDM, but it can help others.

I think you can close this issue :)

**Comment by bonigarcia** [comment] 2020-06-05 11:20
Thanks a lot, @eliasnogueira.

As you said, this is not strictly related to WebDriverManager but the test infrastructure. I am not sure this kind of problem should be in the README, because in this case, we should also explain Xvfb (for example) and many other things.

**Closed by bonigarcia** 2020-06-05 11:20 UTC
Labels: question

**Comment by QA-Rahul** [comment] 2020-06-05 14:24
Hey @eliasnogueira - Thanks a lot for more detail and also for the solution. It works like charm. Thanks a lot.

**Comment by click2sarath** [comment] 2021-03-16 07:41
I exactly tried the same thing but the solution did not work for me

[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
/root/.cache/selenium/chromedriver/linux64/89.0.4389.23/chromedriver: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
Mar 16, 2021 7:37:11 AM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)
[ERROR] Tests run: 31, Failures: 1, Errors: 0, Skipped: 30, Time elapsed: 24.573 s <<< FAILURE! - in TestSuite

**GitYml**

stages:
  - build
  - dev
  - QA
  - staging
  - prod


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  image: markhobson/maven-chrome:jdk-14
  stage: build
  script:
    - mvn compile
  when: manual


.test_template: &test_template
  image: maven:3.6.3-adoptopenjdk-14-openj9
  variables:
    ENVIRONMENT: Dev
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script: mvn test -DBrowser=Chrome -DEnvironment=$ENVIRONMENT -PSmoke
  cache:
    paths:
      - .m2/repository/
      - target/
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit:
        - target/surefire-reports/*.*

dev:
  stage: dev
  <<: *test_template
  allow_failure: false
  only:
    variables:
      - $CI_JOB_STAGE == "dev"
  cache:
    paths:
      - .m2/repository/
      - target/
  except:
    - schedules
  when: manual

please help me

**Comment by tonyskulk** [comment] 2022-02-22 07:26
I have the exact same problem. I am using selenium/selenide and have set headless mode, but it is not working inside a gitlab docker runner with the same exception like above.
