### ISSUE TITLE
webdriver.chrome.binary is ignored

### ISSUE THREAD

**Issue by SiKing** [bonigarcia/webdrivermanager#548] opened 2020-09-08 22:51 UTC
**Description of the problem**: 
When running my tests in CI, I want to use the latest (Chrome-Beta) browser. So I set the property:
```
webdriver.chrome.binary = /usr/bin/google-chrome-beta
```
Unfortunately, webdrivermanager ignores this and detects the previous version, from `/usr/bin/google-chrome`.

It would be desirable if webdrivermanager respected this property.

**Browser and version**: 
All

**Operating system**: 
All

**WebDriverManager version**: 
4.1.0

**WebDriverManager use**: 
I use the webdriver manager via Serenity-BDD https://github.com/serenity-bdd/serenity-core

**Comment by SiKing** [comment] 2020-09-08 23:09
I tried:
```
wdm.browserPath = /usr/bin/google-chrome-beta
```
but I still get the wrong version of chromedriver.

**Comment by SiKing** [comment] 2020-09-08 23:14
As of this writing I am using:
```
+ google-chrome --version
Google Chrome 84.0.4147.135 
+ google-chrome-beta --version
Google Chrome 86.0.4240.22 beta
```

I would like to use version 86, but I always end up with:
```
WebDriverManager - Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
```

**Comment by SiKing** [comment] 2020-09-09 18:50
I had a browse through the source. Apparently `wdm.browserPath` is just that: a path. The name of the binary is hard-wired in the source to `google-chrome`.
A fix for this is not trivial.

**Comment by eliasnogueira** [comment] 2020-09-14 18:35
Can you try to set this as `true` @SiKing ?
```
wdm.useBetaVersions=true
```

**Comment by SiKing** [comment] 2020-09-14 18:44
I still get the same:
```
[INFO] WebDriverManager - Using chromedriver 84.0.4147.30 (since Chrome 84 is installed in your machine)
```

Do I need the `wdm.browserPath` in combination with above?

**Comment by eliasnogueira** [comment] 2020-09-15 07:32
Hi @SiKing I think you can try.
But I think you are writing in the comment said that the browser name is hardcoded.

If the `wdm.browserPath` and the `wdm.useBetaVersions` won't work I will try to change the chrome binary name when you set both.

**Comment by eliasnogueira** [comment] 2020-09-15 09:39
@SiKing I just realized that the `wdm.browserPath` was introduced into version 4.2.0, and your issue is with 4.1.0.
Can you update the library and try to do the test in the previous comment?

**Comment by SiKing** [comment] 2020-09-15 15:41
Finally got it to work! I need:
- version 4.2; version 4.1 does not work
- `wdm.useBetaVersions=true`

I did not use `wdm.browserPath`; that looks like it is only needed when the binary is not in the current path already.

**Comment by SiKing** [comment] 2020-09-16 17:19
I think I must be going crazy!

Last night I ran my full test suite: ~160 tests, running parallel across 4 threads. The first ~10 tests ran with version 86, as I was expecting. Then the remainder of the tests were run with version 84.

I do not understand how this is possible.

**Comment by eliasnogueira** [comment] 2020-09-18 08:59
I will try to reproduce it locally.
Can you tell me if this environment is a headless one and how did you install the Chrome beta @SiKing ?

**Comment by SiKing** [comment] 2020-09-18 14:14
This is on Jenkins, so headless.
Our admin installed Chrome-Beta from an .rpm. It gets updated periodically (weekly) from a cron.

**Comment by bonigarcia** [comment] 2020-09-21 15:37
The `wdm.browserPath` configuration key (or its equivalent method `.browserPath()) should be enough to solve this issue. I have just committed an example of this: [ChromeBetaTest](https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/chrome/ChromeBetaTest.java)

@SiKing Maybe your problem is that you are using Chrome and Chrome beta in the same test suite. Since WebDriverManager caches the found browser version, it can cause problems in this case. The solution should be using `.clearResolutionCache()` as well (in the tests using beta versions, for instance). But I have just discovered a bug in that method. I have committed another path to solve it. It should be available in the next version of wdm, to be released soon, stay tuned.

BTW the expected value of `wdm.browserPath` is not just a path, it is the full browser path. I have explained better in the README.

**Comment by bonigarcia** [comment] 2020-09-21 17:22
@SiKing Please update to WebDriverManager 4.2.1, just released and use `.browserPath()` and `.clearResolutionCache()` as in the example before. It should work.

**Comment by bonigarcia** [comment] 2020-09-21 18:19
Or even better, use version 4.2.2 (former version has a bug related to Edge).

**Comment by SiKing** [comment] 2020-09-23 15:26
This now works.

I used version 4.2.2, and **only** `wdm.browserPath`. In my test suite I do not mix Chrome versions, so I did not use the clear cache thing.
Ran my entire test suite twice, just to be sure.

So just out of curiosity, what does `wdm.useBetaVersions` do?

**Comment by bonigarcia** [comment] 2020-09-23 15:37
The configuration key `wdm.useBetaVersions` is used for beta versions in drivers (i.e. > stable). In this case, it should not be necessary since the `wdm.browserPath` is used to find the browser version, and with that, wdm can match the proper driver version (independently to the stable version).

**Closed** 2020-09-23 15:44 UTC
Labels: question
