### ISSUE TITLE
Cannot access Chrome DevTools from WebDriverManager.chromedriver().browserInDocker()

### ISSUE THREAD

**Issue by seanyyyyyy** [bonigarcia/webdrivermanager#947] opened 2022-11-27 22:46 UTC
**Description of the problem**: 
Running chrome browser in Docker and attempting to access ChromeDriver DevTools
However casting it to the created browser throws an error

**Browser and version**: 
ChromeDriver 107.0.5304.62

**Operating system**: 
Linux

**WebDriverManager version**: 
5.3.1

**WebDriverManager call**: 
WebDriverManager wdm = WebDriverManager.chromedriver().browserInDocker();
WebDriver driver = wdm.create();

DevTools chromeDevTools = ((ChromeDriver) driver).getDevTools();
chromeDevTools.createSession();

**WebDriverManager traces**: 

**Error log**: 
java.lang.ClassCastException at BetTests.java:33

**Comment by bonigarcia** [comment] 2022-11-28 14:01
The method `.browserInDocker()` returns an instance of `RemoteWebDriver`, so that casting is not going to work. Instead, you should use the following:

```
WebDriver augmentedDriver = new Augmenter().augment(driver);
DevTools devTools = ((HasDevTools) augmentedDriver).getDevTools();
```

But even that it is not going to work, since internally WebDriverManager uses the [Aerokube Docker images](https://aerokube.com/images/latest/), and currently, the support for CDP is an [open issue](https://github.com/aerokube/selenoid/issues/1175).

**Comment by batounen** [comment] 2022-12-03 01:14
Suddenly from yesterday ChromeDriver initialization is having issue.

**Throwing:**
- org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
- Caused by: org.openqa.selenium.WebDriverException: Driver server process died prematurely.

Any idea why? Firefox driver is working without any issue.

**Comment by yaggarwal** [comment] 2023-08-21 09:50
@bonigarcia Is there any update on this? When can we expect for DevTools to work with Docker?

**Comment by bonigarcia** [comment] 2023-08-22 12:40
I don't have any news about it, sorry. The support for CDP in Aerokube's images is still an [open issue](https://github.com/aerokube/selenoid/issues/1175).

**Comment by yaggarwal** [comment] 2023-08-23 15:42
@bonigarcia there is an update on that ticket today:
this was released in https://github.com/aerokube/selenoid/releases/tag/1.11.0
Can u check that if possible

**Comment by yaggarwal** [comment] 2023-08-23 15:42
@bonigarcia there is an update on that ticket today:
this was released in https://github.com/aerokube/selenoid/releases/tag/1.11.0
Can u check that if possible

**Comment by yaggarwal** [comment] 2023-08-28 11:52
@batounen any chance to take a look at this?

**Comment by yaggarwal** [comment] 2023-08-28 11:53
@bonigarcia any chance to take a look at this?

**Comment by bonigarcia** [comment] 2023-08-28 11:57
I don't have the time to look into this, sorry.  You can contribute to the project with a PR about it if you need it.

**Comment by bonigarcia** [comment] 2023-10-27 10:35
I managed to implement a test using dockerized browsers through WebDriverManager and CDP:

https://github.com/bonigarcia/webdrivermanager/blob/master/src/test/java/io/github/bonigarcia/wdm/test/docker/DockerChromeCdpTest.java

This will require WebDriverManager 5.6.0, just released.

Unfortunately, I managed to get this test working in local, but not in GitHub Actions. In GH Actions I get a "connection refused" when connecting to http://localhost:4444/ (see [question](https://stackoverflow.com/questions/77373389/connection-refused-when-using-host-network-in-docker-in-github-actions)).

**Comment by bonigarcia** [comment] 2023-10-31 13:05
I confirmed this is also working in GH Actions. For example:

- Test: https://github.com/bonigarcia/selenium-examples/blob/main/src/test/java/io/github/bonigarcia/selenium/remote/DockerWdmChromeCdpTest.java
- Workflow: https://github.com/bonigarcia/selenium-examples/blob/main/.github/workflows/docker-java.yml
- Execution: https://github.com/bonigarcia/selenium-examples/actions/runs/6706576135

For executing in GH Actions, it is important not to run the test after Xvfb is started. For some reason, using Xvfb does not allow us to use port 4444 in the same session.

In summary, the support for CDP through dockerized browsers required the use of the host Docker network, use and WebDriver augmenters, and avoid Xvfb:

```
    WebDriver driver;
    DevTools devTools;
    WebDriverManager wdm = WebDriverManager.chromedriver().browserInDocker()
            .dockerNetworkHost();

    @BeforeEach
    void setupTest() throws Exception {
        assumeThat(isDockerAvailable()).isTrue();
        driver = new Augmenter().augment(wdm.create());
        devTools = ((HasDevTools) driver).getDevTools();
        devTools.createSession();
    }
```

**Closed by bonigarcia** 2023-10-31 13:05 UTC
Labels: enhancement

**Comment by Jbranadev** [comment] 2025-09-13 16:50
Buen día @bonigarcia, deseo te encuentres bien. trate de visualizar el ejemplo que adjuntas, pero no se encuentra disponible.

<img width="1914" height="805" alt="Image" src="https://github.com/user-attachments/assets/ac77a5a5-51dd-4c3f-ab8d-ad1a11464348" />

Quiero poder crear una instancia de devTools cuando tengo un driver iniciado remotamente



`

driverManager = WebDriverManager.chromedriver().browserInDocker()
                     .dockerVolumes(volumenWindows, volumenTestService) // Monta la carpeta local en el volumen dentro del contenedor
                                .dockerDaemonUrl(dockerUrl).enableVnc().enableRecording().timeout(180)
                                .dockerRecordingOutput(rutaVideo); // Convierte Path a String

driver = driverManager.create();


if (driver instanceof HasDevTools) {
                        DevTools devTools = ((HasDevTools) driver).getDevTools();
                        devTools.createSession();
                    
                        // Habilita el monitoreo de red
                        devTools.send(org.openqa.selenium.devtools.v137.network.Network.enable(
                            Optional.empty(), Optional.empty(), Optional.empty()
                        ));
                    
                        // Escucha eventos de inicio y fin de peticiones
                        devTools.addListener(
                            org.openqa.selenium.devtools.v137.network.Network.requestWillBeSent(),
                            event -> LogsJB.info("Petición iniciada: " + event.getRequest().getUrl())
                        );
                        devTools.addListener(
                            org.openqa.selenium.devtools.v137.network.Network.loadingFinished(),
                            event -> LogsJB.info("Petición finalizada: " + event.getRequestId())
                        );
                        //Este codigo es solo para navegadoresweb
                        ChromeDriver driverchrome = (ChromeDriver) driver;

                        interceptor = new NetworkInterceptor(
                                driverchrome,
                                (Filter) next -> req -> {
                                    testContext.getStarted().incrementAndGet(); // Cuenta inicio de petición
                                    try {
                                        return next.execute(req);
                                    } finally {
                                        testContext.getFinished().incrementAndGet(); // Cuenta fin de petición
                                    }
                                }
                        );
                    } else {
                        LogsJB.error("El driver no soporta DevTools");
                    }
                    
                    
`
me crea el driver, pero no me permite crear la instancia de devtools, esto solo me pasa cuando levanto el navegador dentro de docker, si lo levanto en mi maquina host, todo funciona sin problema.

estas son mis versiones de dependencias

implementation 'org.seleniumhq.selenium:selenium-java:4.35.0'
implementation 'org.seleniumhq.selenium:selenium-devtools-v137:4.35.0'
implementation 'io.github.bonigarcia:webdrivermanager:5.9.2'
    implementation 'io.opentelemetry:opentelemetry-api:1.48.0'
    implementation 'io.opentelemetry:opentelemetry-sdk:1.48.0'
    implementation 'io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.48.0'

veo que dentro de docker la versión más reciente de navegador que crea es la 128, entiendo que esta ya tiene soporte para CDP, tu me podrías compartir un ejemplo de CDP, teniendo levantado mi navegador dentro de docker?

desde ya agradezo tu apoyo

**Comment by bonigarcia** [comment] 2025-09-13 17:23
@Jbranadev This was possible previously (see https://github.com/bonigarcia/webdrivermanager/issues/947#issuecomment-1787182543). Unfortunately, I believe this is no longer possible in the latest versions of WebDriverManager (as of version 6, it uses docker-selenium internally).

**Comment by Jbranadev** [comment] 2025-09-20 23:26
@bonigarcia encontre una solución, pero el problema que tengo ahora es que no puedo exponer el puerto en el que se habilita devtools
````
WebDriver driver;
    DevTools devTools;
    WebDriverManager wdm = WebDriverManager.chromedriver()

            .browserInDocker().timeout(180)

            //.dockerNetworkHost()
            //.dockerNetwork("hostbran")
            ;
    //docker network create --driver host hostbran
    //docker network create --driver bridge hostbran
    /*
    netstat -ano | findstr :4444
    curl http://localhost:4444/
    curl http://host.docker.internal:4444/status


    debuggerAddress
    curl http://localhost:42923/json/version

     */

    private DockerClient getDockerClient(String dockerHost) {
        DefaultDockerClientConfig.Builder dockerClientConfigBuilder = DefaultDockerClientConfig.createDefaultConfigBuilder();
        if (!Config.isNullOrEmpty(dockerHost)) {
            dockerClientConfigBuilder.withDockerHost(dockerHost);
        }
        DockerClientConfig dockerClientConfig = dockerClientConfigBuilder.build();
        URI dockerHostUri = dockerClientConfig.getDockerHost();
        ApacheDockerHttpClient dockerHttpClient = (new ApacheDockerHttpClient.Builder()).dockerHost(dockerHostUri).build();
        return DockerClientBuilder.getInstance(dockerClientConfig).withDockerHttpClient(dockerHttpClient).build();
    }

    private DockerClient createDockerClient() {
        String dockerDaemonUrl = null;
        String dockerHost = io.github.bonigarcia.wdm.config.Config.isNullOrEmpty(dockerDaemonUrl) ? DockerHost.fromEnv().endpoint() : dockerDaemonUrl;
        return this.getDockerClient(dockerHost);
    }

    @BeforeTest
    public void createSession() {
        ChromeOptions optionsChrome = new ChromeOptions();
        optionsChrome.addArguments("--ignore-certificate-errors");
        optionsChrome.addArguments("--auto-open-devtools-for-tabs");
        optionsChrome.addArguments("--force-devtools-available");
        // Quiero obtener un puerto libre dinámicamente para usar en remote-debugging-port
        int port;
        try  {
            java.net.ServerSocket socket = new java.net.ServerSocket(0);
            port = socket.getLocalPort();
        }catch (Exception ex){
            LogsJB.fatal("No se ha podido obtener un puerto libre, se usará el 5075 por defecto");
            port = 5075;
        }
        // Ahora puedes usar la variable 'port' para el argumento --remote-debugging-port
        optionsChrome.addArguments("--remote-debugging-port=" +
                port);
        optionsChrome.setAcceptInsecureCerts(true);
        driver = (wdm.capabilities(optionsChrome).create());
//        driver = (wdm.create());
        String containerid=wdm.getDockerBrowserContainerId();
        DockerClient dockerClient = createDockerClient();
        ExposedPort portVariable = ExposedPort.tcp(port);
        // Asignar puertos libres en el host
        Ports portBindings = new Ports();
        portBindings.bind(portVariable, Ports.Binding.bindPort(port));
        //Ahora quiero que al contendor se le libere publicamente el puerto port

        LogsJB.fatal("Driver creado con las siguientes capacidades: "+ImmutableCapabilities.copyOf(((HasCapabilities) driver).getCapabilities()));
        // quiero modificar una capabilities del driver, como lo harías?
        ((HasCapabilities) driver).getCapabilities();
        org.openqa.selenium.WebDriver driver1 = new Augmenter().augment(driver);
        try {
            // Cast the RemoteWebDriver to ChromiumDriver to access DevTools
            // This cast is possible if the remote node is running a Chromium-based browser
            // and the driver on the node is a ChromiumDriver or its subclass.
            LogsJB.fatal("Tipo de driver: " + driver.getClass().getName());
            if (driver instanceof org.openqa.selenium.chromium.ChromiumDriver) {
                org.openqa.selenium.chromium.ChromiumDriver chromiumDriver =
                        (org.openqa.selenium.chromium.ChromiumDriver) driver;

                DevTools devTools = chromiumDriver.getDevTools();
                devTools.createSession();

                // Example: Enable network monitoring and capture requests
                devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));
                devTools.addListener(Network.requestWillBeSent(), request -> {
                    System.out.println("Request URL: " + request.getRequest().getUrl());
                });

                driver.get("https://www.example.com");

                // Perform other actions and interact with DevTools as needed
            } else {
                System.out.println("RemoteWebDriver is not a ChromiumDriver instance. CDP features may not be available.");
            }

        }
        catch (Exception e) {
            LogsJB.fatal("Excepción en DevTools: " + ExceptionUtils.getStackTrace(e));
            LogsJB.waitForOperationComplete();
        }
        finally {
            driver.quit();
        }



        devTools = ((HasDevTools) driver).getDevTools();
        


        devTools.createSession();
    }



````

estoy usando la versión 5.9.2 de webdriver manager, no e actualizado, porque en las nuevas versiones al habilitar VNC, me daba unos problemas con elementos en los que necesitas posar el mouse y se habilitan menus u otras opciones.

Pero ese problema no me preocupa tanto, podemos buscar una solución en nuestro equipo, lo unico que quisiera saber, es que posiblidad hay de que en el metodo 

startBrowserContainer de la clase DockerService, sería posible permitir que el usuario indique si quiere exponer más puertos de los que actualmente tu tienes mapeados?

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/4c941bbf-02e7-4f0b-887a-00a1947a7329" />

Actualmente solo deja libre el puerto del server de selenium, vnc, pero no permite que el usuario indique algo como que quiero exponer el puerto X del contenedor en el puerto Y de mi maquina HOST.

Nos podrías apoyar con esa funcionalidad? 

no se si en las nuevas versiones de web driver manager incluyes algo como eso?
