### ISSUE TITLE
Issue with Latest Chrome Driver Version 74?

### ISSUE THREAD

**Issue by bbarman4u** [bonigarcia/webdrivermanager#318] opened 2019-03-14 14:00 UTC
Currently whenever the tests are executing on windows with latest chrome driver 74.x version being pulled down, we are getting the following error. Tested on machines running windows 7, windows server 2012 among others. Used the stop gap work around to force use 2.46 in the mean time.

So should the 74.x be made the default [here ](https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/versions.properties) ?

> org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 74
> 23:04:25   (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)

**Comment by jacsamell** [comment] 2019-03-14 14:59
Updating to the latest version of webdrivermanager (3.3.0) should fix it. 
The older version wasn't aware of Chrome 73.

**Comment by bonigarcia** [comment] 2019-03-14 15:42
The solution to this problem is upgrading to the latest version of WebDriverManager, i.e. 3.3.0 at the time of this writing. Old versions of WDM simply downloads the latest versions of binaries. Latest version of chromedriver at this moment is 74.*, which is incompatible with Chrome 73 (which is the stable now). But as of version 3, WDM finds out the version of the browser (Chrome in this case), mapping the proper binary (chromedriver). This info is stored internally in the file [versions.properties](https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/versions.properties). If the browser is unknown in the local version, the online master version of that file is read instead.

All in all, you need to upgrade WDM and then resolve the binary as usual:

```
WebDriverManager.chromedriver().setup();
```

Said that, it is possible that the problem still happens using version 3.3.0, at least for a while. Latest versions of WDM uses Java preferences to store persistently the resolved versions for binaries (as a file in Linux/Mac or in the registry in Windows). This value has a time-to-live value, by default 3600 seconds. It might happen that the bad version (chromedriver 74) for the browser (Chrome 73) has been stored. In this case, you can try this:

```
WebDriverManager.chromedriver.clearPreferences();
WebDriverManager.chromedriver().setup();
```
If the problem is solved now, the line `WebDriverManager.chromedriver.clearPreferences();` can (and should) be removed for next executions.

**Comment by bananadine** [comment] 2019-03-14 16:56
I tried it with clearPreferences(); without any luck and i also cleared java temps, ran mvn clean on the project, tried with different brower versions. Nothing...

**Comment by enedelina** [comment] 2019-03-15 08:48
I workaround the issue in a most easiest way ... I copy the driver from folder 73.0.3683.68 and replaced it in 74.0.3729.6. Works for me.

**Comment by sakthi2794** [comment] 2019-03-15 09:17
Updated WebDriver manager dependency version to 3.3.0 and it worked for me.

**Comment by medy75** [comment] 2019-03-18 12:01
I have a same issue even when using WDM 3.3.0
I tried 
```
WebDriverManager.chromedriver().clearPreferences();
WebDriverManager.chromedriver().setup();
```
Still getting
```
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.14.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.11 seconds
```

**Comment by rahol** [comment] 2019-03-19 16:52
Hi, @bonigarcia 

I am also facing the same issue while using WDM , my chromedriver version showing is Latest version of chromedriver is 74.0.3729.6 and my chrome browser version is 72v.

Getting this error :org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 74

I tried your solution but that didn't work for me.!!! 
Can you help me out

**Comment by rahol** [comment] 2019-03-19 17:31
WebDriverManager.chromedriver().version("2.46").setup();

Try this , it work for me

**Comment by medy75** [comment] 2019-03-20 11:02
I am able to force webdriver version by -Dwdm.chromeDriverVersion=73 but its not acceptable for me.

**Comment by RoakyWood** [comment] 2019-03-25 18:17
Hi I am using this with protractor on Windows. This seems to be a Linux thread and I know the issue is closed, but I am seeing the same issue on the Windows version: webdriver-manager v13.0.0 All the folders are different so I can't employ the workaround listed here. Please provide a windows based workaround. Will the underlying defect be fixed? i.e., the mismatch with Chrome version? If this is the wrong place, where would I post this for a solution? (dup of my #313 comment) Cheers - RW

**Comment by RoakyWood** [comment] 2019-03-25 18:40
@medy75 May I ask, where in the code did you force the webdriver version? Folder/File etc. Much Thanks, RW

**Comment by medy75** [comment] 2019-03-25 18:47
@RoakyWood via parameter when running tests with Maven

**Comment by RoakyWood** [comment] 2019-03-25 19:29
@medy75 Thanks, RW

**Comment by RoakyWood** [comment] 2019-03-25 19:54
Although the issue is the same, I am on the wrong forum, I needed npm "webdriver-manager", so I am headed there. Apologies..., RW

**Comment by jadcode** [comment] 2019-03-26 20:18
I have a problem, with the last versión , chromedriver show me this message:

Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

I used the last versión of chromedriver and works fine but not work with webdrivermanager

**Comment by medy75** [comment] 2019-03-26 20:47
@jadcode your problem is not related with this issue. Message about port protection is only warning and has no impact on work of webdriver. If you want a help with setting up your project, use another thread or read documentation carefuly.

**Comment by dayanacgeorge** [comment] 2019-04-15 15:42
Whether this will work when I execute from Jenkins? For my case, the chromedriver is starting but closing/crashing immediately.

**Comment by ddsky** [comment] 2019-04-16 08:07
@medy75 did you find a different solution for getting this to work other than ` -Dwdm.chromeDriverVersion=73`? I have exactly the same problem using WDM 3.4.0 and latest selenium version and I get pretty much the same as you

```
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 3.16.0-4-amd64 x86_64) 
```` 

None of the suggestions in this thread or [313](https://github.com/bonigarcia/webdrivermanager/issues/313) helps.

**Comment by vnktrmn** [comment] 2019-04-23 20:50
I face the same issue on WDM 3.4.0 on a AWS CodeBuild with chrome 65 on it. I forced version("2.36") and version("2.45").setup() but with no luck.

Any suggestions on this is highly appreciated.

My buildspec install phase on codebuild looks something like this :

```
      - apt-get install -y software-properties-common
      - add-apt-repository -y ppa:canonical-chromium-builds/stage
      - apt-get update -y
      - apt-get install -y chromium-browser
```

**Comment by CloCkWeRX** [comment] 2019-04-30 06:37
I found bumping from chromedriver 1.2.0 to 2.1.0+ resolved the issue; assuming it was looking for experimental versions via https://github.com/flavorjones/chromedriver-helper/blob/master/CHANGELOG.md#210---2018-09-18

**Closed** 2019-05-09 14:24 UTC
Labels: duplicate

**Comment by saadmalik956** [comment] 2019-05-16 11:59
Hi, 

Had same problem, but I have downloaded the latest chromedriver, from http://chromedriver.chromium.org/

and FIXED!

Saad Malik

**Comment by Azhagu-selenium** [comment] 2019-08-13 08:40
can any one please help on this !!!!!
**Chrome version :76.0.3809.....**
1.  My POM dependencies as mentioned below . but am getting error is  **session not created: This version of ChromeDriver only supports Chrome version 77**

 
<dependency>
        <groupId>org.testng</groupId>
        <artifactId>testng</artifactId>
        <version>6.8</version>
        <scope>test</scope>
    </dependency>
    
   
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-chrome-driver</artifactId>
    <version>3.141.59</version>
</dependency>

    <dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>3.6.2</version>
    <scope>test</scope>
</dependency>


2. ********** am getting error the below**

[RemoteTestNG] detected TestNG version 6.14.3
1849 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2992 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 77.0.3865.10
3011 [main] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
3012 [main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Azhagu.R\.m2\repository\webdriver\chromedriver\win32\77.0.3865.10\chromedriver.exe
Starting ChromeDriver 77.0.3865.10 (bc3579f611bbc73331171afe020ec7a45e6ccc55-refs/branch-heads/3865@{#93}) on port 22858
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
PASSED: slotrequest1
FAILED: launchpad
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 77
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'CHELENL280', ip: '192.168.225.84', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: driver.version: ChromeDriver

**Comment by SaiNiranjan** [comment] 2019-08-16 18:47
Even I am having similar issue,

Chrome version :76.0.3809
I have 3.6.2 version in my POM.xml 

I tried even downgrading version to 73, 74, 75 but no luck,

WebDriverManager.chromedriver().version("74"); 
WebDriverManager.chromedriver().setup();

**With the version 74, I am getting below error while triggering build from Azure DevOps,**

![buildfail2](https://user-images.githubusercontent.com/7517467/63190365-52f9c600-c023-11e9-8d6a-9f1c7ad63f6a.PNG)


![buildfail](https://user-images.githubusercontent.com/7517467/63190379-59883d80-c023-11e9-936e-ba4bf35803ce.PNG)


--------------*****************************************------------------------------------------------

I am getting similar error with the **version 76**, I am getting below error while triggering build from Azure DevOps.

@bonigarcia Please address this latest issue. Thanks.

**Comment by laxmibala** [comment] 2019-08-19 11:47
My code is working locally but getting this issue with chrome version 74 and WebDrivermanager 3.6.2 while running from jenkin

org.openqa.selenium.WebDriverException: 
unknown error: cannot find Chrome binary
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EPINPUNW0140', ip: '10.22.95.28', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00837C93+1473683]
	Ordinal0 [0x007BADB1+961969]
	Ordinal0 [0x007442E3+475875]

**Comment by ellvix** [comment] 2019-12-17 16:51
Had SessionNotCreatedError, "This version of ChromeDriver only supports Chrome version 77" after my browser auto updated. 

Solved by going to chromedriver.chromium.org, downloading the latest, and then replacing the chromedriver.exe that was buried within my project.
